# generated by datamodel-codegen:
#   filename:  callbacks/agent-turn
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import ConfigDict, Field, RootModel
from jambonz_sdk._models.base import JambonzModel


class Result(Enum):
    """
    Whether the speculative preflight transcript matched the final transcript ('hit'), did not match ('miss'), or was still in progress ('pending').
    """

    hit = "hit"
    miss = "miss"
    pending = "pending"


class Preflight(JambonzModel):
    """
    Early generation (preflight) metrics. Only present when earlyGeneration is enabled.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    result: Result | None = None
    """
    Whether the speculative preflight transcript matched the final transcript ('hit'), did not match ('miss'), or was still in progress ('pending').
    """
    tokens: int | None = None
    """
    Number of preflight tokens that were buffered. Only present on a 'hit'.
    """


class Latency(JambonzModel):
    """
    Latency metrics for this turn, all in milliseconds. Fields are absent when not applicable.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    transcriber_latency: int | None = None
    """
    STT processing latency: time from user stops talking until final transcript received, in milliseconds.
    """
    turn_detection_latency: int | None = None
    """
    Additional wait after final transcript for end-of-turn detection, in milliseconds. Absent when EOT fires before or with the transcript.
    """
    model_latency: int | None = None
    """
    LLM latency: time spent waiting for the first LLM token after the system is ready to prompt, in milliseconds. Absent on a preflight hit.
    """
    voice_latency: int | None = None
    """
    TTS engine latency: time from first text sent to the TTS engine until first audio received back, in milliseconds.
    """
    preflight: Preflight | None = None
    """
    Early generation (preflight) metrics. Only present when earlyGeneration is enabled.
    """


class AgentEventhookEvents1(JambonzModel):
    """
    Events sent to the agent verb's eventHook during a conversation. These are sent as 'agent:event' messages over the WebSocket connection.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["turn_end"]
    """
    Sent at the end of each conversational turn.
    """
    transcript: str
    """
    The user's final speech-to-text transcript for this turn.
    """
    response: str
    """
    The assistant's text response for this turn. May be trimmed to what was actually spoken if the turn was interrupted and alignment tracking is enabled.
    """
    interrupted: bool
    """
    True if the user interrupted the assistant before it finished speaking.
    """
    latency: Latency
    """
    Latency metrics for this turn, all in milliseconds. Fields are absent when not applicable.
    """


class AgentEventhookEvents2(JambonzModel):
    """
    Events sent to the agent verb's eventHook during a conversation. These are sent as 'agent:event' messages over the WebSocket connection.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["user_transcript"]
    """
    Sent when the user's final transcript is available and the system is proceeding to prompt the LLM. This indicates the end of the user's speech input for the current turn.
    """
    transcript: str
    """
    The user's final speech-to-text transcript.
    """


class AgentEventhookEvents3(JambonzModel):
    """
    Events sent to the agent verb's eventHook during a conversation. These are sent as 'agent:event' messages over the WebSocket connection.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["llm_response"]
    """
    Sent when the LLM has finished generating its response for the current turn. Contains the complete response text.
    """
    response: str
    """
    The assistant's complete text response.
    """


class AgentEventhookEvents4(JambonzModel):
    """
    Events sent to the agent verb's eventHook during a conversation. These are sent as 'agent:event' messages over the WebSocket connection.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["user_interruption"]
    """
    Sent when the user barges in (interrupts) while the assistant is speaking. This event has no additional data.
    """


class AgentEventhookEvents(
    RootModel[
        AgentEventhookEvents1
        | AgentEventhookEvents2
        | AgentEventhookEvents3
        | AgentEventhookEvents4
    ]
):
    root: (
        AgentEventhookEvents1
        | AgentEventhookEvents2
        | AgentEventhookEvents3
        | AgentEventhookEvents4
    ) = Field(..., title="Agent EventHook Events")
    """
    Events sent to the agent verb's eventHook during a conversation. These are sent as 'agent:event' messages over the WebSocket connection.
    """
