# generated by datamodel-codegen:
#   filename:  callbacks/amd
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from .base import ActionhookBasePayload


class Type(Enum):
    """
    The AMD event type. IMPORTANT: This field is 'type', NOT 'amd_type'.
    """

    amd_human_detected = "amd_human_detected"
    amd_machine_detected = "amd_machine_detected"
    amd_no_speech_detected = "amd_no_speech_detected"
    amd_decision_timeout = "amd_decision_timeout"
    amd_machine_stopped_speaking = "amd_machine_stopped_speaking"
    amd_tone_detected = "amd_tone_detected"
    amd_tone_timeout = "amd_tone_timeout"
    amd_error = "amd_error"
    amd_stopped = "amd_stopped"


class AmdActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the AMD actionHook when an answering machine detection event occurs. Multiple events may fire during a single call (e.g. amd_machine_detected followed by amd_machine_stopped_speaking or amd_tone_detected).
    """

    type: Type
    """
    The AMD event type. IMPORTANT: This field is 'type', NOT 'amd_type'.
    """
    reason: str | None = None
    """
    Reason for the detection result (e.g. 'short greeting', 'long greeting', 'hint', 'digit count'). Present on amd_human_detected and amd_machine_detected events.
    """
    greeting: str | None = None
    """
    The transcribed greeting text. Present on amd_human_detected and amd_machine_detected events.
    """
    hint: str | None = None
    """
    The voicemail hint that matched, if detection was triggered by hint matching.
    """
    language: str | None = None
    """
    Language code from the transcription (e.g. 'en-US'). Present on amd_human_detected and amd_machine_detected events.
    """
    frequency: float | None = None
    """
    Frequency of the detected beep in Hz. Present on amd_tone_detected events.
    """
    variance: float | None = None
    """
    Frequency variance of the detected beep. Present on amd_tone_detected events.
    """
