# generated by datamodel-codegen:
#   filename:  callbacks/base
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict, Field
from jambonz_sdk._models.base import JambonzModel


class Direction(Enum):
    """
    Call direction.
    """

    inbound = "inbound"
    outbound = "outbound"


class CallStatus(Enum):
    """
    Current call state.
    """

    trying = "trying"
    ringing = "ringing"
    early_media = "early-media"
    in_progress = "in-progress"
    completed = "completed"
    failed = "failed"
    busy = "busy"
    no_answer = "no-answer"
    queued = "queued"


class ActionhookBasePayload(JambonzModel):
    """
    Common fields present in every actionHook callback payload. All verb-specific callback schemas extend this base.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    call_sid: str | None = None
    """
    Unique identifier for this call.
    """
    account_sid: str | None = None
    """
    Account identifier.
    """
    application_sid: str | None = None
    """
    Application identifier.
    """
    direction: Direction | None = None
    """
    Call direction.
    """
    from_: str | None = Field(default=None, alias="from")
    """
    Caller phone number or SIP URI.
    """
    to: str | None = None
    """
    Called phone number or SIP URI.
    """
    call_id: str | None = None
    """
    SIP Call-ID.
    """
    sbc_callid: str | None = None
    """
    SBC-level Call-ID.
    """
    call_status: CallStatus | None = None
    """
    Current call state.
    """
    sip_status: int | None = None
    """
    SIP response code (e.g. 200, 486).
    """
    sip_reason: str | None = None
    """
    SIP reason phrase (e.g. 'OK', 'Busy Here').
    """
    trace_id: str | None = None
    """
    Distributed tracing identifier for correlating logs across jambonz components.
    """
    originating_sip_ip: str | None = None
    """
    IP address of the originating SIP trunk.
    """
    originating_sip_trunk_name: str | None = None
    """
    Name of the originating SIP trunk as configured in jambonz.
    """
    api_base_url: str | None = None
    """
    jambonz REST API base URL. Use this for mid-call control via the REST API.
    """
