# generated by datamodel-codegen:
#   filename:  callbacks/call-status
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class CallTerminationBy(Enum):
    """
    Who terminated the call. 'caller' if the remote party hung up, 'jambonz' if the call was ended by the application (e.g. hangup verb, REST API). Present only on the final status event (completed/failed).
    """

    caller = "caller"
    jambonz = "jambonz"


class CallStatusWebhookPayload(ActionhookBasePayload):
    """
    Payload sent to the call status webhook URL whenever the call state changes (e.g. trying, in-progress, completed). The status webhook is configured at the application level in jambonz. Multiple status events are sent over the life of a call. The final event (completed or failed) includes additional fields like duration and termination cause.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    call_termination_by: CallTerminationBy | None = None
    """
    Who terminated the call. 'caller' if the remote party hung up, 'jambonz' if the call was ended by the application (e.g. hangup verb, REST API). Present only on the final status event (completed/failed).
    """
    duration: int | None = None
    """
    Call duration in seconds. Present only on the final status event (completed/failed).
    """
