# generated by datamodel-codegen:
#   filename:  callbacks/conference-wait
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class ConferenceWaithookPayload(ActionhookBasePayload):
    """
    Payload sent to the conference waitHook while a participant is waiting for the conference to start. The response should contain an array of say, play, and/or pause verbs to play while waiting.
    """

    model_config = ConfigDict(
        extra="allow",
    )
