# generated by datamodel-codegen:
#   filename:  callbacks/conference-status
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, ConfigDict

from .base import ActionhookBasePayload


class Event(Enum):
    """
    The conference event that occurred.
    """

    start = "start"
    end = "end"
    join = "join"
    leave = "leave"
    start_talking = "start-talking"
    stop_talking = "stop-talking"


class ConferenceStatushookPayload(ActionhookBasePayload):
    """
    Payload sent to the conference statusHook when a conference event occurs.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    event: Event
    """
    The conference event that occurred.
    """
    conference_sid: str
    """
    Conference identifier (format: conf:<account_sid>:<conference_name>).
    """
    friendly_name: str | None = None
    """
    The conference name as specified in the conference verb.
    """
    duration: float | None = None
    """
    Time in seconds since the conference started.
    """
    members: int | None = None
    """
    Current number of participants in the conference.
    """
    time: AwareDatetime | None = None
    """
    ISO 8601 timestamp of when the event occurred.
    """
