# generated by datamodel-codegen:
#   filename:  callbacks/conference
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class ConferenceActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the conference verb's actionHook when the participant leaves or the conference ends. Contains only the base call info.
    """

    model_config = ConfigDict(
        extra="allow",
    )
