# generated by datamodel-codegen:
#   filename:  callbacks/dequeue
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class DequeueResult(Enum):
    """
    Outcome of the dequeue. 'complete' — successfully dequeued and bridged; 'timeout' — no queued caller found; 'hangup' — call hung up during bridge.
    """

    complete = "complete"
    timeout = "timeout"
    hangup = "hangup"


class DequeueActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the dequeue verb's actionHook when the dequeue operation completes.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    dequeue_result: DequeueResult
    """
    Outcome of the dequeue. 'complete' — successfully dequeued and bridged; 'timeout' — no queued caller found; 'hangup' — call hung up during bridge.
    """
