# generated by datamodel-codegen:
#   filename:  callbacks/dial-dtmf
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class DialDtmfhookPayload(ActionhookBasePayload):
    """
    Payload sent to the dial dtmfHook when DTMF digits matching the configured pattern are detected during a dial.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    dtmf: str
    """
    The DTMF digit sequence that matched the configured dtmfCapture pattern.
    """
