# generated by datamodel-codegen:
#   filename:  callbacks/dial-hold
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel

from .base import ActionhookBasePayload


class HoldDetail(JambonzModel):
    """
    Details of the hold event.
    """

    from_: str | None = Field(default=None, alias="from")
    """
    SIP From header value.
    """
    to: str | None = None
    """
    SIP To header value.
    """


class DialOnholdhookPayload(ActionhookBasePayload):
    """
    Payload sent to the dial onHoldHook when the remote party places the call on hold. The response should contain say, play, and/or pause verbs to play as hold music. The hook is called repeatedly until the hold ends.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    hold_detail: HoldDetail
    """
    Details of the hold event.
    """
