# generated by datamodel-codegen:
#   filename:  callbacks/dial-refer
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from jambonz_sdk._models.base import JambonzModel

from .base import ActionhookBasePayload


class ReferDetails(JambonzModel):
    """
    Details of the SIP REFER request. Any custom X-* headers on the REFER are also included as snake_cased properties (e.g. X-Override-Number becomes x_override_number).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    sip_refer_to: str | None = None
    """
    Full SIP Refer-To header value.
    """
    refer_to_user: str | None = None
    """
    User part of the Refer-To URI (phone number or SIP user).
    """
    sip_referred_by: str | None = None
    """
    SIP Referred-By header value, if present.
    """
    referred_by_user: str | None = None
    """
    User part of the Referred-By URI, if present.
    """
    sip_user_agent: str | None = None
    """
    User-Agent header from the REFER request.
    """
    referring_call_sid: str | None = None
    """
    Call SID of the leg that sent the REFER.
    """
    referred_call_sid: str | None = None
    """
    Call SID of the leg being referred.
    """


class DialReferhookPayload(ActionhookBasePayload):
    """
    Payload sent to the dial referHook when a SIP REFER is received during an active dial. The response can contain new verbs to execute.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    refer_details: ReferDetails
    """
    Details of the SIP REFER request. Any custom X-* headers on the REFER are also included as snake_cased properties (e.g. X-Override-Number becomes x_override_number).
    """
