# generated by datamodel-codegen:
#   filename:  callbacks/dial
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict, Field

from .base import ActionhookBasePayload


class DialCallStatus(Enum):
    """
    Final status of the outbound (dialed) call leg.
    """

    completed = "completed"
    failed = "failed"
    busy = "busy"
    no_answer = "no-answer"
    trying = "trying"
    ringing = "ringing"
    early_media = "early-media"
    in_progress = "in-progress"


class DialActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the actionHook when a dial verb completes, either because the dialed party hung up, the call was not answered, or an error occurred.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    dial_call_status: DialCallStatus | None = None
    """
    Final status of the outbound (dialed) call leg.
    """
    dial_sip_status: int | None = Field(default=None, examples=[200, 486, 487])
    """
    SIP response code from the dialed party (e.g. 200, 486, 487).
    """
    dial_call_sid: str | None = None
    """
    Call SID of the outbound (dialed) call leg.
    """
    dial_sbc_callid: str | None = None
    """
    SBC-level Call-ID for the outbound (dialed) call leg.
    """
