# generated by datamodel-codegen:
#   filename:  callbacks/enqueue
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class QueueResult(Enum):
    """
    Outcome of the enqueue. 'bridged' — call was dequeued and connected; 'hangup' — caller hung up while waiting; 'leave' — caller executed a leave verb from the waitHook; 'error' — an error occurred during bridging.
    """

    bridged = "bridged"
    hangup = "hangup"
    leave = "leave"
    error = "error"


class EnqueueActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the enqueue actionHook when the enqueue verb completes — i.e. the call was bridged, abandoned, left the queue, or an error occurred.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    queue_sid: str
    """
    Queue identifier in the format 'queue:{account_sid}:{queue_name}'.
    """
    queue_time: int
    """
    Time in seconds the caller spent waiting in the queue.
    """
    queue_result: QueueResult
    """
    Outcome of the enqueue. 'bridged' — call was dequeued and connected; 'hangup' — caller hung up while waiting; 'leave' — caller executed a leave verb from the waitHook; 'error' — an error occurred during bridging.
    """
