# generated by datamodel-codegen:
#   filename:  callbacks/enqueue-wait
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from jambonz_sdk._models.base import JambonzModel


class EnqueueWaithookPayload(JambonzModel):
    """
    Payload sent to the enqueue waitHook while a caller is waiting in the queue. The response should contain an array of say, play, pause, and/or leave verbs. Note: this payload is sparse — it contains queue-specific fields plus call_sid and call_id, but NOT the full base payload fields.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    queue_sid: str
    """
    Queue identifier in the format 'queue:{account_sid}:{queue_name}'.
    """
    queue_time: int
    """
    Time in seconds the caller has been waiting in the queue.
    """
    queue_size: int | None = None
    """
    Total number of callers currently in the queue.
    """
    queue_position: int | None = None
    """
    Caller's current position in the queue (0-based).
    """
    call_sid: str | None = None
    """
    Unique identifier for this call.
    """
    call_id: str | None = None
    """
    SIP Call-ID.
    """
