# generated by datamodel-codegen:
#   filename:  callbacks/gather-partial
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict, Field
from jambonz_sdk._models.base import JambonzModel


class Direction(Enum):
    """
    Call direction.
    """

    inbound = "inbound"
    outbound = "outbound"


class Alternative(JambonzModel):
    transcript: str | None = None
    """
    The partial transcript recognized so far.
    """
    confidence: float | None = None
    """
    Confidence score between 0 and 1.
    """


class Vendor(JambonzModel):
    """
    Vendor-specific STT data. Structure varies by provider.
    """

    name: str | None = None
    """
    STT vendor name (e.g. 'deepgram', 'google', 'aws').
    """
    evt: dict[str, Any] | None = None
    """
    Raw vendor-specific event payload.
    """


class Speech(JambonzModel):
    """
    Interim speech recognition results.
    """

    language_code: str | None = None
    """
    Language code used for recognition (e.g. 'en-US').
    """
    channel_tag: int | None = None
    """
    Audio channel number.
    """
    is_final: bool | None = None
    """
    Always false for partial results.
    """
    alternatives: list[Alternative] | None = None
    """
    Array of recognition alternatives, ordered by confidence.
    """
    vendor: Vendor | None = None
    """
    Vendor-specific STT data. Structure varies by provider.
    """


class GatherPartialTranscriptPayload(JambonzModel):
    """
    Payload sent to the partialResultHook during a gather verb with speech input. Delivers interim (partial) speech recognition results as they arrive, before the gather completes. This hook is informational — the response is ignored and does not replace the verb stack. Note: the base fields use slightly different names than the actionHook payload (e.g. local_sip_address instead of fs_sip_address).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    call_sid: str | None = None
    """
    Unique identifier for this call.
    """
    account_sid: str | None = None
    """
    Account identifier.
    """
    application_sid: str | None = None
    """
    Application identifier.
    """
    direction: Direction | None = None
    """
    Call direction.
    """
    from_: str | None = Field(default=None, alias="from")
    """
    Caller phone number or SIP URI.
    """
    to: str | None = None
    """
    Called phone number or SIP URI.
    """
    call_id: str | None = None
    """
    SIP Call-ID.
    """
    sbc_callid: str | None = None
    """
    SBC-level Call-ID.
    """
    call_status: str | None = None
    """
    Current call state.
    """
    sip_status: int | None = None
    """
    SIP response code.
    """
    sip_reason: str | None = None
    """
    SIP reason phrase.
    """
    trace_id: str | None = None
    """
    Distributed tracing identifier.
    """
    b3: str | None = None
    """
    B3 trace propagation header.
    """
    caller_name: str | None = None
    """
    Caller display name from SIP, if available.
    """
    originating_sip_ip: str | None = None
    """
    IP address of the originating SIP trunk.
    """
    originating_sip_trunk_name: str | None = None
    """
    Name of the originating SIP trunk.
    """
    speech: Speech | None = None
    """
    Interim speech recognition results.
    """
