# generated by datamodel-codegen:
#   filename:  callbacks/gather
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict

from .base import ActionhookBasePayload
from jambonz_sdk._models.base import JambonzModel


class Reason(Enum):
    """
    The reason the gather completed.
    """

    speech_detected = "speechDetected"
    dtmf_detected = "dtmfDetected"
    timeout = "timeout"
    error = "error"
    stt_low_confidence = "stt-low-confidence"


class Alternative(JambonzModel):
    transcript: str | None = None
    """
    The recognized transcript.
    """
    confidence: float | None = None
    """
    Confidence score between 0 and 1.
    """


class Vendor(JambonzModel):
    """
    Vendor-specific STT data. Structure varies by provider.
    """

    name: str | None = None
    """
    STT vendor name (e.g. 'deepgram', 'google', 'aws').
    """
    evt: dict[str, Any] | list[dict[str, Any]] | None = None
    """
    Raw vendor-specific event payload. A single object for simple utterances, or an array of objects when jambonz assembles the final transcript from multiple STT segments. Contains provider-specific fields like word-level timestamps, model info, etc.
    """


class Speech(JambonzModel):
    """
    Speech recognition results, present when reason is speechDetected.
    """

    language_code: str | None = None
    """
    Language code used for recognition (e.g. 'en-US').
    """
    channel_tag: int | None = None
    """
    Audio channel number.
    """
    is_final: bool | None = None
    """
    Whether this is a final (not interim) recognition result.
    """
    alternatives: list[Alternative] | None = None
    """
    Array of recognition alternatives, ordered by confidence.
    """
    vendor: Vendor | None = None
    """
    Vendor-specific STT data. Structure varies by provider.
    """


class GatherActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the actionHook when a gather verb completes, either due to speech detected, DTMF detected, or timeout.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    reason: Reason | None = None
    """
    The reason the gather completed.
    """
    speech: Speech | None = None
    """
    Speech recognition results, present when reason is speechDetected.
    """
    digits: str | None = None
    """
    DTMF digits collected, present when reason is dtmfDetected.
    """
    details: dict[str, Any] | None = None
    """
    Error information if reason is error.
    """
