# generated by datamodel-codegen:
#   filename:  callbacks/listen
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class ListenActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the listen verb's actionHook when the listen verb completes.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    dial_call_duration: int | None = None
    """
    Duration of the listen session in seconds, present if recording was active.
    """
    digits: str | None = None
    """
    DTMF digit that ended the listen, present if finishOnKey was configured and pressed.
    """
