# generated by datamodel-codegen:
#   filename:  callbacks/llm
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class CompletionReason(Enum):
    """
    Reason the LLM session ended.
    """

    normal_conversation_end = "normal conversation end"
    connection_failure = "connection failure"
    disconnect_from_remote_end = "disconnect from remote end"
    server_failure = "server failure"
    server_error = "server error"
    client_error_calling_function = "client error calling function"
    client_error_calling_mcp_function = "client error calling mcp function"


class LlmActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the llm verb's actionHook when the LLM session ends. Applies to all LLM providers (OpenAI, Google, ElevenLabs, Ultravox, and generic voice agents).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    completion_reason: CompletionReason
    """
    Reason the LLM session ended.
    """
    error: Any | None = None
    """
    Error details, present when completion_reason indicates a failure.
    """
