# generated by datamodel-codegen:
#   filename:  callbacks/message
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class MessageStatus(Enum):
    """
    Delivery status of the message.
    """

    success = "success"
    failure = "failure"
    no_carriers = "no carriers"
    smpp_configuration_error = "smpp configuration error"
    system_error = "system error"


class MessageActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the message verb's actionHook with the delivery status of an outbound SMS.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    message_sid: str
    """
    Unique identifier for the message.
    """
    message_status: MessageStatus
    """
    Delivery status of the message.
    """
    carrier: str | None = None
    """
    Name of the carrier used to send the message. Present on success or carrier-level failure.
    """
    carrier_message_id: str | None = None
    """
    Message ID returned by the carrier. Present on success or carrier-level failure.
    """
    message_failure_reason: str | None = None
    """
    Reason for failure. Present when message_status is 'failure' or 'system error'.
    """
