# generated by datamodel-codegen:
#   filename:  callbacks/play
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class Reason(Enum):
    """
    Outcome of playback. 'playCompleted' on success, 'playFailed' on file-not-found or other error.
    """

    play_completed = "playCompleted"
    play_failed = "playFailed"


class Status(Enum):
    """
    Set to 'fail' when playback failed (e.g. file not found).
    """

    fail = "fail"


class PlayActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the play verb's actionHook when playback completes or fails.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    reason: Reason
    """
    Outcome of playback. 'playCompleted' on success, 'playFailed' on file-not-found or other error.
    """
    playback_seconds: int | None = None
    """
    Total playback duration in seconds. Present when reason is 'playCompleted'.
    """
    playback_milliseconds: int | None = None
    """
    Total playback duration in milliseconds. Present when reason is 'playCompleted'.
    """
    playback_last_offset_pos: str | None = None
    """
    Last offset position in the audio stream. Present when reason is 'playCompleted'.
    """
    status: Status | None = None
    """
    Set to 'fail' when playback failed (e.g. file not found).
    """
