# generated by datamodel-codegen:
#   filename:  callbacks/session-redirect
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field

from .base import ActionhookBasePayload


class SessionRedirectPayload(ActionhookBasePayload):
    """
    Payload delivered when a redirect verb transfers the call to a new application or WebSocket endpoint. Contains only the current call state information — unlike session:new, it does not include defaults, env_vars, sip, or service_provider_sid.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    caller_name: str | None = None
    """
    Caller display name from the SIP From header.
    """
    caller_id: str | None = None
    """
    Caller ID value (phone number or SIP user).
    """
    parent_call_sid: str | None = None
    """
    Call SID of the parent call, if applicable.
    """
    fs_sip_address: str | None = None
    """
    Internal SIP address of the FreeSWITCH media server handling this call.
    """
    fs_public_ip: str | None = None
    """
    Public IP address of the FreeSWITCH media server, if available.
    """
    customer_data: dict[str, Any] | None = Field(default=None, alias="customerData")
    """
    Custom data attached to the call via the REST API. Preserved as-is (not snake-cased).
    """
