# generated by datamodel-codegen:
#   filename:  callbacks/session-reconnect
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from .session_new import SessionNewPayload


class SessionReconnectPayload(SessionNewPayload):
    """
    Payload delivered when a WebSocket client reconnects after a disconnection. The payload is identical to the original session:new payload — it is cached from the initial session setup and replayed on reconnect. This allows the application to restore state without needing to re-fetch call details.
    """
