# generated by datamodel-codegen:
#   filename:  callbacks/session-new
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict, Field

from .base import ActionhookBasePayload
from jambonz_sdk._models.base import JambonzModel


class Type(Enum):
    """
    Always 'request' for an incoming INVITE.
    """

    request = "request"


class Source(Enum):
    """
    Origin of the SIP message.
    """

    network = "network"
    application = "application"


class Sip(JambonzModel):
    """
    The raw SIP INVITE message (drachtio SipRequest object, serialized). Only present for WebSocket and HTTP POST transports (not for HTTP GET). See https://drachtio.org/api#sip-request for the full drachtio SipRequest API.
    """

    headers: dict[str, str] | None = Field(
        default=None,
        examples=[
            {
                "X-Authenticated-User": "retell@sip.example.com",
                "X-Override-Number": "+15551234567",
                "From": "<sip:+15083084809@10.0.0.1>;tag=abc123",
                "To": "<sip:+15083728299@jambonz.cloud>",
                "Call-ID": "abc123@10.0.0.1",
            }
        ],
    )
    """
    SIP headers from the INVITE as key-value pairs. Custom headers (X-* headers) from the originating carrier or SIP client are included here. Standard SIP headers like From, To, Contact, Call-ID, Via, etc. are also present.
    """
    body: str | None = None
    """
    SIP message body (typically SDP for INVITE).
    """
    method: str | None = None
    """
    SIP method (always 'INVITE' for session:new).
    """
    uri: str | None = None
    """
    Request-URI from the SIP INVITE.
    """
    called_number: str | None = Field(default=None, alias="calledNumber")
    """
    Phone number extracted from the Request-URI.
    """
    calling_number: str | None = Field(default=None, alias="callingNumber")
    """
    Calling phone number extracted from P-Asserted-Identity or From header.
    """
    type: Type | None = None
    """
    Always 'request' for an incoming INVITE.
    """
    source: Source | None = None
    """
    Origin of the SIP message.
    """
    source_address: str | None = None
    """
    IP address of the sender.
    """
    source_port: str | int | None = None
    """
    Port of the sender.
    """
    protocol: str | None = None
    """
    Transport protocol (e.g. 'udp', 'tcp', 'tls', 'wss').
    """
    payload: list[Any] | None = None
    """
    Message body organized into parts; useful for multipart content.
    """


class Synthesizer(JambonzModel):
    """
    Default TTS settings.
    """

    vendor: str | None = None
    language: str | None = None
    voice: str | None = None


class Recognizer(JambonzModel):
    """
    Default STT settings.
    """

    vendor: str | None = None
    language: str | None = None


class Defaults(JambonzModel):
    """
    Default speech settings for the account (synthesizer and recognizer defaults).
    """

    synthesizer: Synthesizer | None = None
    """
    Default TTS settings.
    """
    recognizer: Recognizer | None = None
    """
    Default STT settings.
    """


class SessionNewPayload(ActionhookBasePayload):
    """
    Payload delivered when a new call arrives. For webhook apps this is the initial POST body; for WebSocket apps it is the `data` property of the first `session:new` message. In the @jambonz/sdk WebSocket transport, this data is available as `session.data`.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    caller_name: str | None = None
    """
    Caller display name from the SIP From header.
    """
    caller_id: str | None = None
    """
    Caller ID value (phone number or SIP user).
    """
    service_provider_sid: str | None = None
    """
    Service provider identifier, if applicable.
    """
    parent_call_sid: str | None = None
    """
    Call SID of the parent call, present when this session was created via the REST API dial (adulting) or when an outbound call leg is promoted to its own session.
    """
    fs_sip_address: str | None = None
    """
    Internal SIP address of the FreeSWITCH media server handling this call.
    """
    fs_public_ip: str | None = None
    """
    Public IP address of the FreeSWITCH media server, if available.
    """
    sip: Sip | None = None
    """
    The raw SIP INVITE message (drachtio SipRequest object, serialized). Only present for WebSocket and HTTP POST transports (not for HTTP GET). See https://drachtio.org/api#sip-request for the full drachtio SipRequest API.
    """
    env_vars: dict[str, Any] | None = Field(
        default=None,
        examples=[
            {
                "RETELL_TRUNK_NAME": "retell-hosted",
                "PSTN_TRUNK_NAME": "my-carrier",
                "DEFAULT_COUNTRY": "US",
            }
        ],
    )
    """
    Application environment variables configured in the jambonz portal. These are the key-value pairs defined in the application's environment variable schema. In the @jambonz/sdk, access via `session.data.env_vars`.
    """
    defaults: Defaults | None = None
    """
    Default speech settings for the account (synthesizer and recognizer defaults).
    """
    customer_data: dict[str, Any] | None = Field(default=None, alias="customerData")
    """
    Custom data attached to the call via the REST API when creating an outbound call. Preserved as-is (not snake-cased).
    """
