# generated by datamodel-codegen:
#   filename:  callbacks/sip-request
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class Result(Enum):
    """
    Whether the SIP request succeeded or failed.
    """

    success = "success"
    failed = "failed"


class SiprequestActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the sip-request verb's actionHook after a SIP request (e.g. INFO, NOTIFY) is sent and a response is received.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    result: Result
    """
    Whether the SIP request succeeded or failed.
    """
    sip_status: int | None = None
    """
    SIP response status code. Present when result is 'success'.
    """
    err: str | None = None
    """
    Error message. Present when result is 'failed'.
    """
