# generated by datamodel-codegen:
#   filename:  callbacks/sip-refer-event
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict
from jambonz_sdk._models.base import JambonzModel


class SipReferEventhookPayload(JambonzModel):
    """
    Payload sent to the sip-refer eventHook when a SIP NOTIFY is received with transfer status updates.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    event: Literal["transfer-status"]
    """
    Event type — always 'transfer-status' for REFER notifications.
    """
    call_status: int
    """
    SIP status code from the NOTIFY sipfrag body (e.g. 100 for trying, 180 for ringing, 200 for success).
    """
