# generated by datamodel-codegen:
#   filename:  callbacks/sip-refer
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from .base import ActionhookBasePayload


class SipreferActionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the sip-refer verb's actionHook when the REFER completes. Sent once the REFER response is received, or after a final NOTIFY arrives.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    refer_status: int
    """
    SIP status code from the REFER response (e.g. 202 for accepted, 4xx/5xx for failure).
    """
    final_referred_call_status: int | None = None
    """
    Final SIP status of the referred call, extracted from a NOTIFY sipfrag. Present only when the REFER was accepted (202) and a final NOTIFY was received.
    """
