# generated by datamodel-codegen:
#   filename:  callbacks/transcribe
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict

from .base import ActionhookBasePayload
from jambonz_sdk._models.base import JambonzModel


class Alternative(JambonzModel):
    transcript: str | None = None
    """
    The recognized transcript.
    """
    confidence: float | None = None
    """
    Confidence score between 0 and 1.
    """


class Speech(JambonzModel):
    """
    Speech recognition results, present when the STT engine returns alternatives.
    """

    language_code: str | None = None
    """
    Language code used for recognition (e.g. 'en-US').
    """
    channel_tag: int | None = None
    """
    Audio channel number.
    """
    is_final: bool | None = None
    """
    Whether this is a final (not interim) recognition result.
    """
    alternatives: list[Alternative] | None = None
    """
    Array of recognition alternatives, ordered by confidence.
    """


class SpeechEvent(JambonzModel):
    """
    Speech event data, present when the STT engine returns a typed event (e.g. end of utterance).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str | None = None
    """
    Event type from the STT vendor.
    """


class TranscribeTranscriptionhookPayload(ActionhookBasePayload):
    """
    Payload sent to the transcriptionHook when a transcription result is received from the STT engine.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    speech: Speech | None = None
    """
    Speech recognition results, present when the STT engine returns alternatives.
    """
    speech_event: SpeechEvent | None = None
    """
    Speech event data, present when the STT engine returns a typed event (e.g. end of utterance).
    """
    stt_latency_ms: str | None = None
    """
    STT latency in milliseconds.
    """
    stt_talkspurts: str | None = None
    """
    JSON-encoded array of talkspurt timing data.
    """
    stt_start_time: str | None = None
    """
    STT recognition start time.
    """
    stt_stop_time: str | None = None
    """
    STT recognition stop time.
    """
    stt_usage: Any | None = None
    """
    STT usage data from the vendor.
    """
