# generated by datamodel-codegen:
#   filename:  callbacks/transcribe-translation
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from pydantic import ConfigDict

from .base import ActionhookBasePayload
from jambonz_sdk._models.base import JambonzModel


class Translation(JambonzModel):
    """
    Translation result data.
    """

    channel: int
    """
    Audio channel number (1 or 2).
    """
    language: str
    """
    Target language code for the translation.
    """
    translation: str
    """
    The translated text.
    """


class TranscribeTranslationhookPayload(ActionhookBasePayload):
    """
    Payload sent to the translationHook when a translation result is received.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    translation: Translation
    """
    Translation result data.
    """
