# generated by datamodel-codegen:
#   filename:  callbacks/transcribe-translation
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from jambonz_sdk._models.base import JambonzModel

from .base import ActionhookBasePayload


class Translation(JambonzModel):
    """
    Translation result data.
    """

    channel: int
    """
    Audio channel number (1 or 2).
    """
    language: str
    """
    Target language code for the translation.
    """
    translation: str
    """
    The translated text.
    """


class TranscribeTranslationhookPayload(ActionhookBasePayload):
    """
    Payload sent to the translationHook when a translation result is received.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    translation: Translation
    """
    Translation result data.
    """
