# generated by datamodel-codegen:
#   filename:  callbacks/tts-streaming-event
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict, Field, RootModel

from jambonz_sdk._models.base import JambonzModel


class TtsStreamingEvent1(JambonzModel):
    """
    Events sent to the '/streaming-event' WebSocket endpoint during TTS streaming. These are sent as 'tts:streaming-event' messages. The tts_spoken event is only sent when trackTtsPlayout is enabled via the config verb.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_type: Literal["stream_open"]
    """
    The TTS streaming connection has been established.
    """


class TtsStreamingEvent2(JambonzModel):
    """
    Events sent to the '/streaming-event' WebSocket endpoint during TTS streaming. These are sent as 'tts:streaming-event' messages. The tts_spoken event is only sent when trackTtsPlayout is enabled via the config verb.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_type: Literal["stream_closed"]
    """
    The TTS streaming connection has been closed.
    """


class TtsStreamingEvent3(JambonzModel):
    """
    Events sent to the '/streaming-event' WebSocket endpoint during TTS streaming. These are sent as 'tts:streaming-event' messages. The tts_spoken event is only sent when trackTtsPlayout is enabled via the config verb.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_type: Literal["stream_paused"]
    """
    TTS streaming has been paused.
    """


class TtsStreamingEvent4(JambonzModel):
    """
    Events sent to the '/streaming-event' WebSocket endpoint during TTS streaming. These are sent as 'tts:streaming-event' messages. The tts_spoken event is only sent when trackTtsPlayout is enabled via the config verb.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_type: Literal["stream_resumed"]
    """
    TTS streaming has been resumed.
    """


class TtsStreamingEvent5(JambonzModel):
    """
    Events sent to the '/streaming-event' WebSocket endpoint during TTS streaming. These are sent as 'tts:streaming-event' messages. The tts_spoken event is only sent when trackTtsPlayout is enabled via the config verb.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_type: Literal["user_interruption"]
    """
    The user interrupted (barged in) during TTS playout, causing the stream to be cleared.
    """


class TtsStreamingEvent6(JambonzModel):
    """
    Events sent to the '/streaming-event' WebSocket endpoint during TTS streaming. These are sent as 'tts:streaming-event' messages. The tts_spoken event is only sent when trackTtsPlayout is enabled via the config verb.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_type: Literal["tts_spoken"]
    """
    Reports the actual text that was spoken via TTS. Sent on utterance completion or when the user barges in. Only sent when trackTtsPlayout is enabled via the config verb. Requires a TTS vendor that supports alignment data (e.g. ElevenLabs).
    """
    text: str
    """
    The text that was actually spoken before completion or interruption.
    """
    bargein: bool
    """
    True if the user barged in (interrupted) before the TTS finished speaking. False if the utterance completed normally.
    """


class TtsStreamingEvent(
    RootModel[
        TtsStreamingEvent1
        | TtsStreamingEvent2
        | TtsStreamingEvent3
        | TtsStreamingEvent4
        | TtsStreamingEvent5
        | TtsStreamingEvent6
    ]
):
    root: (
        TtsStreamingEvent1
        | TtsStreamingEvent2
        | TtsStreamingEvent3
        | TtsStreamingEvent4
        | TtsStreamingEvent5
        | TtsStreamingEvent6
    ) = Field(..., title="TTS Streaming Event")
    """
    Events sent to the '/streaming-event' WebSocket endpoint during TTS streaming. These are sent as 'tts:streaming-event' messages. The tts_spoken event is only sent when trackTtsPlayout is enabled via the config verb.
    """
