# generated by datamodel-codegen:
#   filename:  callbacks/verb-status
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict

from jambonz_sdk._models.base import JambonzModel


class Event(Enum):
    """
    The verb lifecycle event.
    """

    starting = "starting"
    finished = "finished"
    start_playback = "start-playback"
    stop_playback = "stop-playback"
    kill_playback = "kill-playback"
    dtmf_bargein_detected = "dtmf-bargein-detected"
    speech_bargein_detected = "speech-bargein-detected"
    synthesized_audio = "synthesized-audio"


class VerbStatusEvent(JambonzModel):
    """
    Real-time verb lifecycle events sent over WebSocket when notifyEvents is enabled on the session. These are informational — no response is expected.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    event: Event
    """
    The verb lifecycle event.
    """
    verb: str | None = None
    """
    The verb name (e.g. 'say', 'play', 'gather'). Present on synthesized-audio, start-playback, stop-playback, kill-playback, and dtmf/speech-bargein events.
    """
    name: str | None = None
    """
    The verb name. Present on 'starting' and 'finished' events (these use 'name' instead of 'verb').
    """
    id: str | None = None
    """
    The verb instance id, if one was assigned by the application.
    """
    vendor: str | None = None
    """
    TTS vendor name. Present on synthesized-audio events.
    """
    language: str | None = None
    """
    TTS language code. Present on synthesized-audio events.
    """
    characters: int | None = None
    """
    Number of characters synthesized. Present on synthesized-audio events when not served from cache.
    """
    elapsed_time: float | None = None
    """
    TTS round-trip time in milliseconds. Present on synthesized-audio events when not served from cache.
    """
    served_from_cache: bool | None = None
    """
    Whether the TTS audio was served from cache. Present on synthesized-audio events.
    """
