# generated by datamodel-codegen:
#   filename:  components/actionHookDelayAction
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any

from pydantic import Field
from jambonz_sdk._models.base import JambonzModel


class ActionHookDelayAction(JambonzModel):
    """
    Configuration for what to do when an actionHook (webhook) takes a long time to respond. Allows playing interim content (e.g. 'please wait' messages, hold music) while waiting for the webhook response, with configurable retry and give-up behavior.
    """

    enabled: bool | None = None
    """
    Whether to enable delay handling for actionHooks.
    """
    no_response_timeout: float | None = Field(
        default=None, alias="noResponseTimeout", examples=[3, 5]
    )
    """
    Time in seconds to wait before executing the delay actions. If the webhook responds before this timeout, the delay actions are skipped.
    """
    no_response_give_up_timeout: float | None = Field(
        default=None, alias="noResponseGiveUpTimeout", examples=[30, 60]
    )
    """
    Total time in seconds to wait for a webhook response before giving up and executing the giveUpActions.
    """
    retries: float | None = None
    """
    Number of times to retry the delay actions while still waiting for the webhook response.
    """
    actions: list[dict[str, Any]] | None = None
    """
    An array of jambonz verbs to execute while waiting for the webhook response. Typically 'say' or 'play' verbs with messages like 'please hold'.
    """
    give_up_actions: list[dict[str, Any]] | None = Field(default=None, alias="giveUpActions")
    """
    An array of jambonz verbs to execute if the webhook never responds within the giveUpTimeout. Typically an error message and/or hangup.
    """
