# generated by datamodel-codegen:
#   filename:  components/actionHook
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import Field, RootModel

from . import auth
from jambonz_sdk._models.base import JambonzModel


class Method(Enum):
    """
    The HTTP method to use. Only applies to webhook applications.
    """

    get = "GET"
    post = "POST"


class ActionHook1(JambonzModel):
    """
    A hook specification with URL and additional options.
    """

    url: str
    """
    The URL to invoke.
    """
    method: Method | None = "POST"
    """
    The HTTP method to use. Only applies to webhook applications.
    """
    basic_auth: auth.Auth | None = Field(default=None, alias="basicAuth")
    """
    Basic authentication credentials to include in the request.
    """


class ActionHook(RootModel[str | ActionHook1]):
    root: str | ActionHook1 = Field(..., title="ActionHook")
    """
    A webhook or websocket callback that jambonz invokes when a verb completes. Reports verb results (e.g. speech recognition from 'gather', dial outcome) and receives the next verbs to execute. In webhook mode: jambonz POSTs to this URL and the HTTP response body is the next verb array. In WebSocket mode: this value becomes an event name emitted on the session — bind session.on('/hookName', (evt) => {...}) and respond with session.reply() (NOT session.send()). The callback payload always includes 'reason' plus verb-specific fields (e.g. 'speech', 'digits' for gather). Can be a simple URL/path string or an object with additional options.
    """
