# generated by datamodel-codegen:
#   filename:  components/amd
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from pydantic import ConfigDict, Field

from . import actionHook
from . import recognizer as recognizer_1
from jambonz_sdk._models.base import JambonzModel


class Timers(JambonzModel):
    """
    Timer settings controlling AMD detection windows.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    no_speech_timeout_ms: float | None = Field(default=5000, alias="noSpeechTimeoutMs")
    """
    Milliseconds to wait for any speech before returning amd_no_speech_detected.
    """
    decision_timeout_ms: float | None = Field(default=15000, alias="decisionTimeoutMs")
    """
    Milliseconds before returning amd_decision_timeout if no determination is made.
    """
    tone_timeout_ms: float | None = Field(default=20000, alias="toneTimeoutMs")
    """
    Milliseconds to wait for beep/tone detection.
    """
    greeting_completion_timeout_ms: float | None = Field(
        default=2000, alias="greetingCompletionTimeoutMs"
    )
    """
    Milliseconds of silence after speech before determining the machine greeting is complete. Automatically reduced to 1000ms if a beep is detected.
    """


class AnsweringMachineDetection(JambonzModel):
    """
    Configuration for answering machine detection (AMD). Detects whether an outbound or inbound call was answered by a human or a machine. Used as a nested property on the 'config' or 'dial' verb. IMPORTANT: AMD runs asynchronously in the background. When using AMD with the 'config' verb, you MUST follow it with a 'pause' verb (e.g. pause({ length: 25 })) to keep the call alive while AMD detection runs. Without a pause, the call will end immediately after config completes.
    """

    action_hook: actionHook.ActionHook = Field(..., alias="actionHook")
    """
    Webhook to receive AMD events (amd_human_detected, amd_machine_detected, amd_no_speech_detected, amd_decision_timeout, amd_machine_stopped_speaking, amd_tone_detected, amd_error, amd_stopped).
    """
    threshold_word_count: float | None = Field(default=9, alias="thresholdWordCount")
    """
    Number of spoken words in a greeting that triggers an amd_machine_detected result.
    """
    digit_count: float | None = Field(default=0, alias="digitCount")
    """
    Number of digits in a greeting to trigger detection. 0 disables digit-based detection.
    """
    timers: Timers | None = None
    """
    Timer settings controlling AMD detection windows.
    """
    recognizer: recognizer_1.Recognizer | None = None
    """
    Override the STT recognizer used for AMD speech detection. When omitted, AMD uses the session default recognizer with enhancedModel enabled.
    """
