# generated by datamodel-codegen:
#   filename:  components/auth
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations
from jambonz_sdk._models.base import JambonzModel


class Auth(JambonzModel):
    """
    Basic authentication credentials, used for authenticating with external services such as websocket endpoints or SIP registrars.
    """

    username: str
    """
    The username for authentication.
    """
    password: str
    """
    The password for authentication.
    """
