# generated by datamodel-codegen:
#   filename:  components/bidirectionalAudio
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from pydantic import Field
from jambonz_sdk._models.base import JambonzModel


class BidirectionalAudio(JambonzModel):
    """
    Configuration for bidirectional audio streaming over a websocket connection. When enabled, the remote websocket endpoint can send audio back to jambonz to be played to the caller.
    """

    enabled: bool | None = None
    """
    Whether to enable bidirectional audio on the websocket connection.
    """
    streaming: bool | None = None
    """
    If true, audio is streamed continuously rather than sent as complete messages.
    """
    sample_rate: float | None = Field(
        default=None, alias="sampleRate", examples=[8000, 16000, 24000]
    )
    """
    The sample rate in Hz for bidirectional audio.
    """
