# generated by datamodel-codegen:
#   filename:  components/fillerNoise
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from pydantic import Field
from jambonz_sdk._models.base import JambonzModel


class FillerNoise(JambonzModel):
    """
    Configuration for playing background filler noise (e.g. keyboard typing, hold music) while the application is processing and the caller would otherwise hear silence. Commonly used during LLM response generation to indicate the system is working.
    """

    enable: bool
    """
    Whether to enable filler noise.
    """
    url: str | None = Field(default=None, examples=["https://example.com/sounds/typing.wav"])
    """
    URL of the audio file to play as filler noise. Should be a short, loopable audio clip.
    """
    start_delay_secs: float | None = Field(default=None, alias="startDelaySecs", examples=[1, 2])
    """
    Number of seconds to wait before starting filler noise. Prevents filler noise from playing during brief processing pauses.
    """
