# generated by datamodel-codegen:
#   filename:  components/llm-base
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field

from . import actionHook
from jambonz_sdk._models.base import JambonzModel


class Auth(JambonzModel):
    """
    Authentication credentials for the LLM vendor API.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    api_key: str | None = Field(default=None, alias="apiKey")
    """
    The API key for the LLM vendor.
    """


class McpServer(JambonzModel):
    url: str
    """
    The URL of the MCP server.
    """
    auth: dict[str, Any] | None = None
    """
    Authentication for the MCP server.
    """
    roots: list[dict[str, Any]] | None = None
    """
    MCP root definitions.
    """


class LlmBaseProperties(JambonzModel):
    """
    Shared properties for llm, s2s, and vendor-specific s2s verb schemas.
    """

    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    vendor: str | None = Field(
        default=None,
        examples=[
            "openai",
            "anthropic",
            "google",
            "groq",
            "deepseek",
            "deepgram",
            "ultravox",
            "custom",
        ],
    )
    """
    The LLM vendor to use.
    """
    model: str | None = Field(
        default=None, examples=["gpt-4o", "claude-sonnet-4-20250514", "gemini-2.0-flash"]
    )
    """
    The specific model to use from the vendor.
    """
    auth: Auth | None = None
    """
    Authentication credentials for the LLM vendor API.
    """
    connect_options: dict[str, Any] | None = Field(default=None, alias="connectOptions")
    """
    Additional connection options for the LLM vendor, such as custom base URLs or API versions.
    """
    llm_options: dict[str, Any] | None = Field(
        default=None,
        alias="llmOptions",
        examples=[
            {
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful customer service agent for Acme Corp.",
                    }
                ],
                "temperature": 0.7,
            }
        ],
    )
    """
    Configuration passed to the LLM including the system prompt, temperature, tools/functions, and other model parameters. The structure varies by vendor but typically includes 'messages' (conversation history), 'temperature', 'tools' (function definitions), and 'maxTokens'.
    """
    mcp_servers: list[McpServer] | None = Field(default=None, alias="mcpServers")
    """
    Model Context Protocol servers to connect to. MCP servers provide tools that the LLM can invoke during the conversation.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the LLM conversation ends. Receives conversation details and should return the next verbs to execute.
    """
    event_hook: actionHook.ActionHook | None = Field(default=None, alias="eventHook")
    """
    A webhook invoked for real-time events during the LLM conversation (e.g. tool calls, transcription events).
    """
    tool_hook: actionHook.ActionHook | None = Field(default=None, alias="toolHook")
    """
    A webhook invoked when the LLM calls a tool/function. Receives the tool name and arguments, and should return the tool result.
    """
    events: list[str] | None = None
    """
    List of event types to receive via the eventHook.
    """
