# generated by datamodel-codegen:
#   filename:  components/recognizer-assemblyAiOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class ServiceVersion(Enum):
    """
    AssemblyAI streaming API version.
    """

    v2 = "v2"
    v3 = "v3"


class AssemblyaiRecognizerOptions(JambonzModel):
    """
    AssemblyAI-specific STT options. Only applies when recognizer vendor is 'assemblyai'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    api_key: str | None = Field(default=None, alias="apiKey")
    """
    AssemblyAI API key. Overrides credentials configured in jambonz.
    """
    service_version: ServiceVersion | None = Field(default=None, alias="serviceVersion")
    """
    AssemblyAI streaming API version.
    """
    speech_model: str | None = Field(default=None, alias="speechModel")
    """
    AssemblyAI speech model to use for recognition.
    """
    format_turns: bool | None = Field(default=None, alias="formatTurns")
    """
    Enable turn-level formatting.
    """
    end_of_turn_confidence_threshold: float | None = Field(
        default=None, alias="endOfTurnConfidenceThreshold"
    )
    """
    Confidence threshold for end-of-turn detection.
    """
    min_end_of_turn_silence_when_confident: float | None = Field(
        default=None, alias="minEndOfTurnSilenceWhenConfident"
    )
    """
    Minimum silence duration (seconds) to trigger end-of-turn when confidence is met.
    """
    max_turn_silence: float | None = Field(default=None, alias="maxTurnSilence")
    """
    Maximum silence duration (seconds) before forcing end-of-turn.
    """
    min_turn_silence: float | None = Field(default=None, alias="minTurnSilence")
    """
    Minimum silence duration (seconds) before allowing end-of-turn.
    """
    keyterms: list[str] | None = None
    """
    List of key terms to boost in recognition.
    """
    prompt: str | None = None
    """
    Prompt to guide the recognition model.
    """
    language_detection: bool | None = Field(default=None, alias="languageDetection")
    """
    Enable automatic language detection.
    """
    vad_threshold: float | None = Field(default=None, alias="vadThreshold")
    """
    Voice activity detection threshold.
    """
    inactivity_timeout: float | None = Field(default=None, alias="inactivityTimeout")
    """
    Timeout (seconds) for inactivity before closing the stream.
    """
