# generated by datamodel-codegen:
#   filename:  components/recognizer-deepgramOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class Redact(Enum):
    """
    Redact sensitive information from transcripts.
    """

    pci = "pci"
    numbers = "numbers"
    true = "true"
    ssn = "ssn"


class DeepgramRecognizerOptions(JambonzModel):
    """
    Deepgram-specific STT options. Only applies when recognizer vendor is 'deepgram'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    deepgram_stt_uri: str | None = Field(default=None, alias="deepgramSttUri")
    """
    Custom Deepgram STT endpoint URI.
    """
    deepgram_stt_use_tls: bool | None = Field(default=None, alias="deepgramSttUseTls")
    """
    Whether to use TLS when connecting to the Deepgram STT endpoint.
    """
    api_key: str | None = Field(default=None, alias="apiKey")
    """
    Deepgram API key. Overrides the key configured in jambonz.
    """
    tier: str | None = None
    """
    Deepgram model tier.
    """
    model: str | None = None
    """
    Deepgram model name (e.g. 'nova-2', 'nova-2-general').
    """
    custom_model: str | None = Field(default=None, alias="customModel")
    """
    ID of a custom-trained Deepgram model.
    """
    version: str | None = None
    """
    Model version.
    """
    punctuate: bool | None = None
    """
    Enable automatic punctuation.
    """
    smart_formatting: bool | None = Field(default=None, alias="smartFormatting")
    """
    Enable Deepgram smart formatting (dates, numbers, etc.).
    """
    no_delay: bool | None = Field(default=None, alias="noDelay")
    """
    Disable Deepgram's internal buffering for lower latency.
    """
    profanity_filter: bool | None = Field(default=None, alias="profanityFilter")
    """
    Filter profanity from transcripts.
    """
    redact: Redact | None = None
    """
    Redact sensitive information from transcripts.
    """
    diarize: bool | None = None
    """
    Enable speaker diarization.
    """
    diarize_version: str | None = Field(default=None, alias="diarizeVersion")
    """
    Diarization model version.
    """
    ner: bool | None = None
    """
    Enable named entity recognition.
    """
    multichannel: bool | None = None
    """
    Enable multichannel processing.
    """
    alternatives: float | None = None
    """
    Number of alternative transcripts to return.
    """
    numerals: bool | None = None
    """
    Convert spoken numbers to digits.
    """
    search: list[str] | None = None
    """
    Terms to search for in the transcript.
    """
    replace: list[str] | None = None
    """
    Terms to replace in the transcript.
    """
    keywords: list[str] | None = None
    """
    Keywords to boost recognition for.
    """
    keyterms: list[str] | None = None
    """
    Key terms to boost recognition for.
    """
    endpointing: bool | float | None = None
    """
    Endpointing sensitivity. Boolean to enable/disable, or number of milliseconds.
    """
    utterance_end_ms: float | None = Field(default=None, alias="utteranceEndMs")
    """
    Milliseconds of silence to detect end of utterance.
    """
    short_utterance: bool | None = Field(default=None, alias="shortUtterance")
    """
    Optimize for short utterances.
    """
    vad_turnoff: float | None = Field(default=None, alias="vadTurnoff")
    """
    Milliseconds of silence before VAD turns off.
    """
    tag: str | None = None
    """
    Tag to associate with the request for tracking.
    """
    filler_words: bool | None = Field(default=None, alias="fillerWords")
    """
    Include filler words (um, uh) in transcript.
    """
    eot_threshold: float | None = Field(default=None, alias="eotThreshold")
    """
    End-of-turn confidence threshold (0-1).
    """
    eot_timeout_ms: float | None = Field(default=None, alias="eotTimeoutMs")
    """
    End-of-turn timeout in milliseconds.
    """
    mip_opt_out: bool | None = Field(default=None, alias="mipOptOut")
    """
    Opt out of Deepgram's model improvement program.
    """
    entity_prompt: str | None = Field(default=None, alias="entityPrompt")
    """
    Prompt to guide entity detection.
    """
    eager_eot_threshold: float | None = Field(default=None, alias="eagerEotThreshold")
    """
    Eager end-of-turn threshold for faster response.
    """
