# generated by datamodel-codegen:
#   filename:  components/recognizer-ibmOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class IbmRecognizerOptions(JambonzModel):
    """
    IBM Watson Speech-to-Text specific options. Only applies when recognizer vendor is 'ibm'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    stt_api_key: str | None = Field(default=None, alias="sttApiKey")
    """
    IBM STT API key. Overrides credentials configured in jambonz.
    """
    stt_region: str | None = Field(default=None, alias="sttRegion")
    """
    IBM STT region.
    """
    tts_api_key: str | None = Field(default=None, alias="ttsApiKey")
    """
    IBM TTS API key.
    """
    tts_region: str | None = Field(default=None, alias="ttsRegion")
    """
    IBM TTS region.
    """
    instance_id: str | None = Field(default=None, alias="instanceId")
    """
    IBM Watson instance ID.
    """
    model: str | None = None
    """
    Recognition model name.
    """
    language_customization_id: str | None = Field(default=None, alias="languageCustomizationId")
    """
    ID of a custom language model.
    """
    acoustic_customization_id: str | None = Field(default=None, alias="acousticCustomizationId")
    """
    ID of a custom acoustic model.
    """
    base_model_version: str | None = Field(default=None, alias="baseModelVersion")
    """
    Base model version to use.
    """
    watson_metadata: str | None = Field(default=None, alias="watsonMetadata")
    """
    Customer ID metadata for data labeling.
    """
    watson_learning_opt_out: bool | None = Field(default=None, alias="watsonLearningOptOut")
    """
    Opt out of IBM data collection for service improvements.
    """
