# generated by datamodel-codegen:
#   filename:  components/recognizer-verbioOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from jambonz_sdk._models.base import JambonzModel


class VerbioRecognizerOptions(JambonzModel):
    """
    Verbio-specific STT options. Only applies when recognizer vendor is 'verbio'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    enable_formatting: bool | None = None
    """
    Enable text formatting of results.
    """
    enable_diarization: bool | None = None
    """
    Enable speaker diarization.
    """
    topic: float | None = None
    """
    Topic ID for domain-specific recognition.
    """
    inline_grammar: str | None = None
    """
    Inline SRGS grammar for constrained recognition.
    """
    grammar_uri: str | None = None
    """
    URI of an external grammar resource.
    """
    label: str | None = None
    """
    Label for the recognition session.
    """
    recognition_timeout: float | None = None
    """
    Maximum recognition duration in seconds.
    """
    speech_complete_timeout: float | None = None
    """
    Silence duration in seconds after complete speech.
    """
    speech_incomplete_timeout: float | None = None
    """
    Silence duration in seconds after incomplete speech.
    """
