# generated by datamodel-codegen:
#   filename:  components/recognizer-googleOptions
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict, Field
from jambonz_sdk._models.base import JambonzModel


class ServiceVersion(Enum):
    """
    Google Speech-to-Text API version.
    """

    v1 = "v1"
    v2 = "v2"


class GoogleRecognizerOptions(JambonzModel):
    """
    Google Speech-to-Text specific options. Only applies when recognizer vendor is 'google'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    service_version: ServiceVersion | None = Field(default=None, alias="serviceVersion")
    """
    Google Speech-to-Text API version.
    """
    recognizer_id: str | None = Field(default=None, alias="recognizerId")
    """
    ID of a Google Speech recognizer resource (v2 only).
    """
    speech_start_timeout_ms: float | None = Field(default=None, alias="speechStartTimeoutMs")
    """
    Timeout in milliseconds to wait for speech to start.
    """
    speech_end_timeout_ms: float | None = Field(default=None, alias="speechEndTimeoutMs")
    """
    Timeout in milliseconds to detect end of speech.
    """
    enable_voice_activity_events: bool | None = Field(
        default=None, alias="enableVoiceActivityEvents"
    )
    """
    Enable voice activity detection events.
    """
    transcript_normalization: list[Any] | None = Field(
        default=None, alias="transcriptNormalization"
    )
    """
    Array of transcript normalization rules.
    """
