# generated by datamodel-codegen:
#   filename:  components/recognizer
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import Field, confloat

from jambonz_sdk._models.base import JambonzModel

from . import (
    recognizer_assemblyAiOptions,
    recognizer_awsOptions,
    recognizer_azureOptions,
    recognizer_cobaltOptions,
    recognizer_customOptions,
    recognizer_deepgramOptions,
    recognizer_elevenlabsOptions,
    recognizer_gladiaOptions,
    recognizer_googleOptions,
    recognizer_houndifyOptions,
    recognizer_ibmOptions,
    recognizer_nuanceOptions,
    recognizer_nvidiaOptions,
    recognizer_openaiOptions,
    recognizer_sonioxOptions,
    recognizer_speechmaticsOptions,
    recognizer_verbioOptions,
)
from . import vad as vad_1


class Hints(JambonzModel):
    phrase: str
    boost: float | None = None


class InteractionType(Enum):
    """
    A hint to the recognizer about the type of interaction, which can improve accuracy.
    """

    unspecified = "unspecified"
    discussion = "discussion"
    presentation = "presentation"
    phone_call = "phone_call"
    voicemail = "voicemail"
    voice_search = "voice_search"
    voice_command = "voice_command"
    dictation = "dictation"


class FilterMethod(Enum):
    """
    How filtered vocabulary words should be handled in the transcript.
    """

    remove = "remove"
    mask = "mask"
    tag = "tag"


class OutputFormat(Enum):
    """
    The level of detail in recognition results.
    """

    simple = "simple"
    detailed = "detailed"


class ProfanityOption(Enum):
    """
    How profanity should be handled in results.
    """

    masked = "masked"
    removed = "removed"
    raw = "raw"


class Recognizer(JambonzModel):
    """
    Configuration for speech-to-text recognition. Specifies the STT vendor, language, and vendor-specific options. Can be set at the session level via the 'config' verb or overridden per-verb (e.g. on 'gather').
    """

    vendor: str = Field(
        ...,
        examples=[
            "google",
            "aws",
            "microsoft",
            "deepgram",
            "nuance",
            "ibm",
            "nvidia",
            "soniox",
            "cobalt",
            "assemblyai",
            "speechmatics",
            "openai",
            "houndify",
            "gladia",
            "elevenlabs",
            "verbio",
            "custom",
        ],
    )
    """
    The STT vendor to use. Must match a vendor configured in the jambonz platform.
    """
    label: str | None = None
    """
    An optional label identifying a specific credential set for this vendor. Used when multiple credentials are configured for the same vendor.
    """
    language: str | None = Field(default=None, examples=["en-US", "en-GB", "es-ES", "fr-FR"])
    """
    The language code for speech recognition, in BCP-47 format.
    """
    fallback_vendor: str | None = Field(default=None, alias="fallbackVendor")
    """
    A backup STT vendor to use if the primary vendor fails or is unavailable.
    """
    fallback_label: str | None = Field(default=None, alias="fallbackLabel")
    """
    Credential label for the fallback vendor.
    """
    fallback_language: str | None = Field(default=None, alias="fallbackLanguage")
    """
    Language code to use with the fallback vendor.
    """
    vad: vad_1.VAD | None = None
    """
    Voice activity detection settings for this recognizer.
    """
    autogenerate_prompt: bool | None = Field(default=None, alias="autogeneratePrompt")
    """
    If true, automatically generate a prompt for the STT vendor based on context (e.g. TTS voice, language). Supported by vendors that accept prompts for recognition guidance.
    """
    hints: list[str | Hints] | None = Field(
        default=None,
        examples=[
            ["jambonz", "drachtio", "SIP", "WebRTC"],
            [{"phrase": "jambonz", "boost": 20}, {"phrase": "drachtio", "boost": 10}],
        ],
    )
    """
    An array of words or phrases that the recognizer should favor. Each item can be a plain string or an object with 'phrase' and optional 'boost' properties.
    """
    hints_boost: float | None = Field(default=None, alias="hintsBoost")
    """
    A boost factor for hint words. Higher values increase the likelihood of recognizing hinted words. Vendor-specific range.
    """
    alt_languages: list[str] | None = Field(
        default=None, alias="altLanguages", examples=[["es-ES", "fr-FR"]]
    )
    """
    Additional languages the recognizer should listen for simultaneously. Enables multilingual recognition.
    """
    profanity_filter: bool | None = Field(default=None, alias="profanityFilter")
    """
    If true, the vendor will attempt to filter profanity from transcription results.
    """
    interim: bool | None = None
    """
    If true, return interim (partial) transcription results as they become available, before the utterance is complete.
    """
    single_utterance: bool | None = Field(default=None, alias="singleUtterance")
    """
    If true, recognition stops after the first complete utterance is detected.
    """
    dual_channel: bool | None = Field(default=None, alias="dualChannel")
    """
    If true, send separate audio channels for each call leg (caller and callee) to the recognizer.
    """
    separate_recognition_per_channel: bool | None = Field(
        default=None, alias="separateRecognitionPerChannel"
    )
    """
    If true, perform independent recognition on each audio channel. Requires dualChannel.
    """
    punctuation: bool | None = None
    """
    If true, enable automatic punctuation in transcription results.
    """
    enhanced_model: bool | None = Field(default=None, alias="enhancedModel")
    """
    If true, use an enhanced (premium) recognition model if available from the vendor.
    """
    words: bool | None = None
    """
    If true, include word-level timing information in transcription results.
    """
    diarization: bool | None = None
    """
    If true, enable speaker diarization to identify different speakers in the audio.
    """
    diarization_min_speakers: float | None = Field(default=None, alias="diarizationMinSpeakers")
    """
    Minimum number of speakers expected. Used to guide the diarization algorithm.
    """
    diarization_max_speakers: float | None = Field(default=None, alias="diarizationMaxSpeakers")
    """
    Maximum number of speakers expected. Used to guide the diarization algorithm.
    """
    interaction_type: InteractionType | None = Field(default=None, alias="interactionType")
    """
    A hint to the recognizer about the type of interaction, which can improve accuracy.
    """
    naics_code: float | None = Field(default=None, alias="naicsCode")
    """
    North American Industry Classification System code. Some vendors use this to improve domain-specific accuracy.
    """
    identify_channels: bool | None = Field(default=None, alias="identifyChannels")
    """
    If true, identify and label which channel each transcription segment came from.
    """
    vocabulary_name: str | None = Field(default=None, alias="vocabularyName")
    """
    Name of a custom vocabulary resource configured at the vendor for improved recognition of specialized terms.
    """
    vocabulary_filter_name: str | None = Field(default=None, alias="vocabularyFilterName")
    """
    Name of a vocabulary filter configured at the vendor for masking or removing specific words.
    """
    filter_method: FilterMethod | None = Field(default=None, alias="filterMethod")
    """
    How filtered vocabulary words should be handled in the transcript.
    """
    model: str | None = Field(
        default=None, examples=["latest_long", "phone_call", "nova-2", "chirp"]
    )
    """
    The specific recognition model to use. Model names are vendor-specific.
    """
    output_format: OutputFormat | None = Field(default=None, alias="outputFormat")
    """
    The level of detail in recognition results.
    """
    profanity_option: ProfanityOption | None = Field(default=None, alias="profanityOption")
    """
    How profanity should be handled in results.
    """
    request_snr: bool | None = Field(default=None, alias="requestSnr")
    """
    If true, request signal-to-noise ratio information in results.
    """
    initial_speech_timeout_ms: float | None = Field(
        default=None, alias="initialSpeechTimeoutMs", examples=[5000]
    )
    """
    Time in milliseconds to wait for initial speech before timing out.
    """
    azure_service_endpoint: str | None = Field(default=None, alias="azureServiceEndpoint")
    """
    Custom Azure Speech Services endpoint URL. Only applies when vendor is 'microsoft'.
    """
    azure_stt_endpoint_id: str | None = Field(default=None, alias="azureSttEndpointId")
    """
    Azure custom speech endpoint ID for using a custom-trained model. Only applies when vendor is 'microsoft'.
    """
    asr_dtmf_termination_digit: str | None = Field(
        default=None, alias="asrDtmfTerminationDigit", examples=["#"]
    )
    """
    A DTMF digit that terminates speech recognition when pressed.
    """
    asr_timeout: float | None = Field(default=None, alias="asrTimeout")
    """
    Maximum time in seconds to wait for a complete recognition result.
    """
    fast_recognition_timeout: float | None = Field(default=None, alias="fastRecognitionTimeout")
    """
    Timeout in seconds for fast recognition mode. Shorter timeout for quick responses.
    """
    min_confidence: confloat(ge=0.0, le=1.0) | None = Field(default=None, alias="minConfidence")
    """
    Minimum confidence score (0-1) required to accept a recognition result. Results below this threshold are discarded.
    """
    deepgram_options: recognizer_deepgramOptions.DeepgramRecognizerOptions | None = Field(
        default=None, alias="deepgramOptions"
    )
    google_options: recognizer_googleOptions.GoogleRecognizerOptions | None = Field(
        default=None, alias="googleOptions"
    )
    aws_options: recognizer_awsOptions.AwsRecognizerOptions | None = Field(
        default=None, alias="awsOptions"
    )
    azure_options: recognizer_azureOptions.AzureRecognizerOptions | None = Field(
        default=None, alias="azureOptions"
    )
    nuance_options: recognizer_nuanceOptions.NuanceRecognizerOptions | None = Field(
        default=None, alias="nuanceOptions"
    )
    ibm_options: recognizer_ibmOptions.IbmRecognizerOptions | None = Field(
        default=None, alias="ibmOptions"
    )
    nvidia_options: recognizer_nvidiaOptions.NvidiaRecognizerOptions | None = Field(
        default=None, alias="nvidiaOptions"
    )
    soniox_options: recognizer_sonioxOptions.SonioxRecognizerOptions | None = Field(
        default=None, alias="sonioxOptions"
    )
    cobalt_options: recognizer_cobaltOptions.CobaltRecognizerOptions | None = Field(
        default=None, alias="cobaltOptions"
    )
    assembly_ai_options: recognizer_assemblyAiOptions.AssemblyaiRecognizerOptions | None = Field(
        default=None, alias="assemblyAiOptions"
    )
    speechmatics_options: recognizer_speechmaticsOptions.SpeechmaticsRecognizerOptions | None = (
        Field(default=None, alias="speechmaticsOptions")
    )
    openai_options: recognizer_openaiOptions.OpenaiRecognizerOptions | None = Field(
        default=None, alias="openaiOptions"
    )
    houndify_options: recognizer_houndifyOptions.HoundifyRecognizerOptions | None = Field(
        default=None, alias="houndifyOptions"
    )
    gladia_options: recognizer_gladiaOptions.GladiaRecognizerOptions | None = Field(
        default=None, alias="gladiaOptions"
    )
    elevenlabs_options: recognizer_elevenlabsOptions.ElevenlabsRecognizerOptions | None = Field(
        default=None, alias="elevenlabsOptions"
    )
    verbio_options: recognizer_verbioOptions.VerbioRecognizerOptions | None = Field(
        default=None, alias="verbioOptions"
    )
    custom_options: recognizer_customOptions.CustomRecognizerOptions | None = Field(
        default=None, alias="customOptions"
    )
