# generated by datamodel-codegen:
#   filename:  components/recognizer-gladiaOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict

from jambonz_sdk._models.base import JambonzModel


class GladiaRecognizerOptions(JambonzModel):
    """
    Gladia-specific STT options. Only applies when recognizer vendor is 'gladia'. See Gladia API documentation for available options.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
