# generated by datamodel-codegen:
#   filename:  components/recognizer-cobaltOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class CobaltRecognizerOptions(JambonzModel):
    """
    Cobalt-specific STT options. Only applies when recognizer vendor is 'cobalt'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    server_uri: str | None = Field(default=None, alias="serverUri")
    """
    Cobalt server URI.
    """
    enable_confusion_network: bool | None = Field(default=None, alias="enableConfusionNetwork")
    """
    Enable confusion network output.
    """
    metadata: str | None = None
    """
    Metadata string to pass to the server.
    """
    compiled_context_data: str | None = Field(default=None, alias="compiledContextData")
    """
    Compiled context data for biasing recognition.
    """
    word_time_offsets: bool | None = Field(default=None, alias="wordTimeOffsets")
    """
    Include word-level timestamps.
    """
    context_token: str | None = Field(default=None, alias="contextToken")
    """
    Context token for server-side context.
    """
