# generated by datamodel-codegen:
#   filename:  components/recognizer-azureOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class LanguageIdMode(Enum):
    """
    Language identification mode when using multiple languages.
    """

    at_start = "AtStart"
    continuous = "Continuous"


class SpeechRecognitionMode(Enum):
    """
    Speech recognition mode optimized for the interaction type.
    """

    conversation = "CONVERSATION"
    dictation = "DICTATION"
    interactive = "INTERACTIVE"


class AzureRecognizerOptions(JambonzModel):
    """
    Azure Speech Services specific options. Only applies when recognizer vendor is 'microsoft'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    speech_segmentation_silence_timeout_ms: float | None = Field(
        default=None, alias="speechSegmentationSilenceTimeoutMs"
    )
    """
    Silence timeout in milliseconds for speech segmentation.
    """
    post_processing: str | None = Field(default=None, alias="postProcessing")
    """
    Post-processing mode for transcription results.
    """
    audio_logging: bool | None = Field(default=None, alias="audioLogging")
    """
    Enable audio logging for diagnostics.
    """
    language_id_mode: LanguageIdMode | None = Field(default=None, alias="languageIdMode")
    """
    Language identification mode when using multiple languages.
    """
    speech_recognition_mode: SpeechRecognitionMode | None = Field(
        default=None, alias="speechRecognitionMode"
    )
    """
    Speech recognition mode optimized for the interaction type.
    """
