# generated by datamodel-codegen:
#   filename:  components/recognizer-awsOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class VocabularyFilterMethod(Enum):
    """
    How filtered vocabulary words should be handled.
    """

    remove = "remove"
    mask = "mask"
    tag = "tag"


class AwsRecognizerOptions(JambonzModel):
    """
    AWS Transcribe specific options. Only applies when recognizer vendor is 'aws'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    access_key: str | None = Field(default=None, alias="accessKey")
    """
    AWS access key ID. Overrides credentials configured in jambonz.
    """
    secret_key: str | None = Field(default=None, alias="secretKey")
    """
    AWS secret access key.
    """
    security_token: str | None = Field(default=None, alias="securityToken")
    """
    AWS temporary security token (for STS/assumed roles).
    """
    region: str | None = None
    """
    AWS region for the Transcribe service.
    """
    vocabulary_name: str | None = Field(default=None, alias="vocabularyName")
    """
    Name of a custom vocabulary to use.
    """
    vocabulary_filter_name: str | None = Field(default=None, alias="vocabularyFilterName")
    """
    Name of a vocabulary filter to apply.
    """
    vocabulary_filter_method: VocabularyFilterMethod | None = Field(
        default=None, alias="vocabularyFilterMethod"
    )
    """
    How filtered vocabulary words should be handled.
    """
    language_model_name: str | None = Field(default=None, alias="languageModelName")
    """
    Name of a custom language model.
    """
    pii_entity_types: list[str] | None = Field(default=None, alias="piiEntityTypes")
    """
    PII entity types to identify (e.g. 'BANK_ACCOUNT_NUMBER', 'CREDIT_DEBIT_NUMBER').
    """
    pii_identify_entities: bool | None = Field(default=None, alias="piiIdentifyEntities")
    """
    Enable PII entity identification.
    """
