# generated by datamodel-codegen:
#   filename:  components/recognizer-nvidiaOptions
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field
from jambonz_sdk._models.base import JambonzModel


class NvidiaRecognizerOptions(JambonzModel):
    """
    NVIDIA Riva specific options. Only applies when recognizer vendor is 'nvidia'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    riva_uri: str | None = Field(default=None, alias="rivaUri")
    """
    NVIDIA Riva server URI.
    """
    max_alternatives: float | None = Field(default=None, alias="maxAlternatives")
    """
    Maximum number of alternative transcripts.
    """
    profanity_filter: bool | None = Field(default=None, alias="profanityFilter")
    """
    Filter profanity from results.
    """
    punctuation: bool | None = None
    """
    Enable automatic punctuation.
    """
    word_time_offsets: bool | None = Field(default=None, alias="wordTimeOffsets")
    """
    Include word-level timestamps.
    """
    verbatim_transcripts: bool | None = Field(default=None, alias="verbatimTranscripts")
    """
    Return verbatim (unformatted) transcripts.
    """
    custom_configuration: dict[str, Any] | None = Field(default=None, alias="customConfiguration")
    """
    Custom Riva configuration parameters.
    """
