# generated by datamodel-codegen:
#   filename:  components/recognizer-sonioxOptions
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field
from jambonz_sdk._models.base import JambonzModel


class Storage(JambonzModel):
    """
    Soniox storage configuration for persisting transcripts.
    """

    id: str | None = None
    """
    Storage ID.
    """
    title: str | None = None
    """
    Storage title.
    """
    disable_store_audio: bool | None = Field(default=None, alias="disableStoreAudio")
    """
    Disable audio storage.
    """
    disable_store_transcript: bool | None = Field(default=None, alias="disableStoreTranscript")
    """
    Disable transcript storage.
    """
    disable_search: bool | None = Field(default=None, alias="disableSearch")
    """
    Disable search indexing.
    """
    metadata: dict[str, Any] | None = None
    """
    Custom metadata.
    """


class SonioxRecognizerOptions(JambonzModel):
    """
    Soniox-specific STT options. Only applies when recognizer vendor is 'soniox'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    api_key: str | None = Field(default=None, alias="apiKey")
    """
    Soniox API key.
    """
    model: str | None = None
    """
    Soniox recognition model.
    """
    endpoint_detection: bool | None = Field(default=None, alias="endpointDetection")
    """
    Enable endpoint detection.
    """
    profanity_filter: bool | None = Field(default=None, alias="profanityFilter")
    """
    Filter profanity from results.
    """
    speech_context: str | None = Field(default=None, alias="speechContext")
    """
    Speech context for improved recognition.
    """
    client_request_reference: str | None = Field(default=None, alias="clientRequestReference")
    """
    Client request reference for tracking.
    """
    storage: Storage | None = None
    """
    Soniox storage configuration for persisting transcripts.
    """
