# generated by datamodel-codegen:
#   filename:  components/recognizer-speechmaticsOptions
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict
from jambonz_sdk._models.base import JambonzModel


class Profile(Enum):
    """
    Speechmatics profile.
    """

    adaptive = "adaptive"
    agile = "agile"
    smart = "smart"
    external = "external"


class SpeakerDiarizationConfig(JambonzModel):
    speaker_sensitivity: float | None = None
    max_speakers: float | None = None


class ConversationConfig(JambonzModel):
    end_of_utterance_silence_trigger: float | None = None


class MaxDelayMode(Enum):
    """
    Delay mode.
    """

    fixed = "fixed"
    flexible = "flexible"


class PunctuationOverrides(JambonzModel):
    permitted_marks: list[str] | None = None
    sensitivity: float | None = None


class AudioFilteringConfig(JambonzModel):
    volume_threshold: float


class TranscriptFilteringConfig(JambonzModel):
    remove_disfluencies: bool


class TranscriptionConfig(JambonzModel):
    """
    Speechmatics transcription configuration.
    """

    language: str | None = None
    """
    Language code.
    """
    domain: str | None = None
    """
    Domain model.
    """
    additional_vocab: list[Any] | None = None
    """
    Additional vocabulary entries.
    """
    diarization: str | None = None
    """
    Diarization mode.
    """
    speaker_diarization_config: SpeakerDiarizationConfig | None = None
    conversation_config: ConversationConfig | None = None
    enable_partials: bool | None = None
    """
    Enable partial transcripts.
    """
    max_delay: float | None = None
    """
    Maximum delay in seconds.
    """
    max_delay_mode: MaxDelayMode | None = None
    """
    Delay mode.
    """
    output_locale: str | None = None
    """
    Output locale for formatting.
    """
    punctuation_overrides: PunctuationOverrides | None = None
    operating_point: str | None = None
    """
    Operating point (standard or enhanced).
    """
    enable_entities: bool | None = None
    """
    Enable entity detection.
    """
    audio_filtering_config: AudioFilteringConfig | None = None
    transcript_filtering_config: TranscriptFilteringConfig | None = None


class TranslationConfig(JambonzModel):
    """
    Speechmatics translation configuration.
    """

    target_languages: list[str]
    """
    Target languages for translation.
    """
    enable_partials: bool | None = None
    """
    Enable partial translations.
    """


class Type(Enum):
    applause = "applause"
    music = "music"
    laughter = "laughter"


class AudioEventsConfig(JambonzModel):
    """
    Audio event detection configuration.
    """

    types: list[Type] | None = None
    """
    Audio event types to detect.
    """


class SpeechmaticsRecognizerOptions(JambonzModel):
    """
    Speechmatics-specific STT options. Only applies when recognizer vendor is 'speechmatics'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    host: str | None = None
    """
    Speechmatics host URL.
    """
    profile: Profile | None = None
    """
    Speechmatics profile.
    """
    transcription_config: TranscriptionConfig | None = None
    """
    Speechmatics transcription configuration.
    """
    translation_config: TranslationConfig | None = None
    """
    Speechmatics translation configuration.
    """
    audio_events_config: AudioEventsConfig | None = None
    """
    Audio event detection configuration.
    """
