# generated by datamodel-codegen:
#   filename:  components/recognizer-openaiOptions
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict, Field
from jambonz_sdk._models.base import JambonzModel


class PromptTemplates(JambonzModel):
    """
    Templates for dynamic prompt generation.
    """

    hints_template: str | None = Field(default=None, alias="hintsTemplate")
    """
    Template for injecting hints into the prompt.
    """
    conversation_history_template: str | None = Field(
        default=None, alias="conversationHistoryTemplate"
    )
    """
    Template for injecting conversation history.
    """


class InputAudioNoiseReduction(Enum):
    """
    Input audio noise reduction mode.
    """

    near_field = "near_field"
    far_field = "far_field"


class Type(Enum):
    """
    Turn detection strategy.
    """

    none = "none"
    server_vad = "server_vad"
    semantic_vad = "semantic_vad"


class Eagerness(Enum):
    """
    How eagerly the model should respond.
    """

    low = "low"
    medium = "medium"
    high = "high"
    auto = "auto"


class TurnDetection(JambonzModel):
    """
    Turn detection configuration for the OpenAI Realtime API.
    """

    type: Type
    """
    Turn detection strategy.
    """
    eagerness: Eagerness | None = None
    """
    How eagerly the model should respond.
    """
    threshold: float | None = None
    """
    VAD activation threshold (0-1).
    """
    prefix_padding_ms: float | None = None
    """
    Milliseconds of audio to include before detected speech.
    """
    silence_duration_ms: float | None = None
    """
    Milliseconds of silence to detect end of speech.
    """


class OpenaiRecognizerOptions(JambonzModel):
    """
    OpenAI Whisper/Realtime specific STT options. Only applies when recognizer vendor is 'openai'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    api_key: str | None = Field(default=None, alias="apiKey")
    """
    OpenAI API key. Overrides credentials configured in jambonz.
    """
    model: str | None = None
    """
    OpenAI STT model name.
    """
    prompt: str | None = None
    """
    Prompt to guide the recognition model.
    """
    prompt_templates: PromptTemplates | None = Field(default=None, alias="promptTemplates")
    """
    Templates for dynamic prompt generation.
    """
    language: str | None = None
    """
    Language code for recognition.
    """
    input_audio_noise_reduction: InputAudioNoiseReduction | None = None
    """
    Input audio noise reduction mode.
    """
    turn_detection: TurnDetection | None = None
    """
    Turn detection configuration for the OpenAI Realtime API.
    """
