# generated by datamodel-codegen:
#   filename:  components/recognizer-customOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class CustomRecognizerOptions(JambonzModel):
    """
    Options for custom STT vendors. Only applies when recognizer vendor is 'custom'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    auth_token: str | None = Field(default=None, alias="authToken")
    """
    Authentication token for the custom STT service.
    """
    uri: str | None = None
    """
    WebSocket URI of the custom STT service.
    """
    sample_rate: float | None = Field(default=None, alias="sampleRate")
    """
    Audio sample rate in Hz.
    """
    options: dict[str, Any] | None = None
    """
    Additional vendor-specific options passed through to the custom service.
    """
