# generated by datamodel-codegen:
#   filename:  components/recognizer-elevenlabsOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class CommitStrategy(Enum):
    """
    How audio chunks are committed. 'manual' for explicit commits, 'vad' for voice activity detection.
    """

    manual = "manual"
    vad = "vad"


class ElevenlabsRecognizerOptions(JambonzModel):
    """
    ElevenLabs-specific STT options. Only applies when recognizer vendor is 'elevenlabs'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    include_timestamps: bool | None = Field(default=None, alias="includeTimestamps")
    """
    Include word-level timestamps in results.
    """
    commit_strategy: CommitStrategy | None = Field(default=None, alias="commitStrategy")
    """
    How audio chunks are committed. 'manual' for explicit commits, 'vad' for voice activity detection.
    """
    vad_silence_threshold_secs: float | None = Field(default=None, alias="vadSilenceThresholdSecs")
    """
    Silence duration in seconds to trigger VAD commit.
    """
    vad_threshold: float | None = Field(default=None, alias="vadThreshold")
    """
    VAD activation threshold.
    """
    min_speech_duration_ms: float | None = Field(default=None, alias="minSpeechDurationMs")
    """
    Minimum speech duration in milliseconds to accept.
    """
    min_silence_duration_ms: float | None = Field(default=None, alias="minSilenceDurationMs")
    """
    Minimum silence duration in milliseconds to trigger end of speech.
    """
    enable_logging: bool | None = Field(default=None, alias="enableLogging")
    """
    Enable server-side logging.
    """
