# generated by datamodel-codegen:
#   filename:  components/recognizer-nuanceOptions
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict, Field
from jambonz_sdk._models.base import JambonzModel


class UtteranceDetectionMode(Enum):
    """
    How utterance boundaries are detected.
    """

    single = "single"
    multiple = "multiple"
    disabled = "disabled"


class ResultType(Enum):
    """
    Type of results to return.
    """

    final = "final"
    partial = "partial"
    immutable_partial = "immutable_partial"


class Formatting(JambonzModel):
    """
    Formatting options for recognition results.
    """

    scheme: str
    """
    Formatting scheme name.
    """
    options: dict[str, Any]
    """
    Scheme-specific formatting options.
    """


class Type(Enum):
    undefined_resource_type = "undefined_resource_type"
    wordset = "wordset"
    compiled_wordset = "compiled_wordset"
    domain_lm = "domain_lm"
    speaker_profile = "speaker_profile"
    grammar = "grammar"
    settings = "settings"


class ExternalReference(JambonzModel):
    """
    External resource reference.
    """

    type: Type | None = None
    uri: str | None = None
    max_load_failures: bool | None = Field(default=None, alias="maxLoadFailures")
    request_timeout_ms: float | None = Field(default=None, alias="requestTimeoutMs")
    headers: dict[str, Any] | None = None


class WeightName(Enum):
    default_weight = "defaultWeight"
    lowest = "lowest"
    low = "low"
    medium = "medium"
    high = "high"
    highest = "highest"


class Reuse(Enum):
    undefined_reuse = "undefined_reuse"
    low_reuse = "low_reuse"
    high_reuse = "high_reuse"


class Resource(JambonzModel):
    external_reference: ExternalReference | None = Field(default=None, alias="externalReference")
    """
    External resource reference.
    """
    inline_wordset: str | None = Field(default=None, alias="inlineWordset")
    """
    Inline wordset JSON string.
    """
    builtin: str | None = None
    """
    Built-in grammar name.
    """
    inline_grammar: str | None = Field(default=None, alias="inlineGrammar")
    """
    Inline SRGS grammar.
    """
    wakeup_word: list[str] | None = Field(default=None, alias="wakeupWord")
    """
    Wakeup words.
    """
    weight_name: WeightName | None = Field(default=None, alias="weightName")
    weight_value: float | None = Field(default=None, alias="weightValue")
    reuse: Reuse | None = None


class NuanceRecognizerOptions(JambonzModel):
    """
    Nuance Mix specific options. Only applies when recognizer vendor is 'nuance'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    client_id: str | None = Field(default=None, alias="clientId")
    """
    Nuance Mix client ID.
    """
    secret: str | None = None
    """
    Nuance Mix client secret.
    """
    krypton_endpoint: str | None = Field(default=None, alias="kryptonEndpoint")
    """
    Custom Nuance Krypton endpoint URL.
    """
    topic: str | None = None
    """
    Recognition topic (domain).
    """
    utterance_detection_mode: UtteranceDetectionMode | None = Field(
        default=None, alias="utteranceDetectionMode"
    )
    """
    How utterance boundaries are detected.
    """
    punctuation: bool | None = None
    """
    Enable automatic punctuation.
    """
    profanity_filter: bool | None = Field(default=None, alias="profanityFilter")
    """
    Filter profanity from results.
    """
    include_tokenization: bool | None = Field(default=None, alias="includeTokenization")
    """
    Include tokenization data in results.
    """
    discard_speaker_adaptation: bool | None = Field(default=None, alias="discardSpeakerAdaptation")
    """
    Discard speaker adaptation data.
    """
    suppress_call_recording: bool | None = Field(default=None, alias="suppressCallRecording")
    """
    Suppress call recording on the Nuance side.
    """
    mask_load_failures: bool | None = Field(default=None, alias="maskLoadFailures")
    """
    Mask resource load failures.
    """
    suppress_initial_capitalization: bool | None = Field(
        default=None, alias="suppressInitialCapitalization"
    )
    """
    Suppress initial capitalization of results.
    """
    allow_zero_base_lm_weight: bool | None = Field(default=None, alias="allowZeroBaseLmWeight")
    """
    Allow zero base language model weight.
    """
    filter_wakeup_word: bool | None = Field(default=None, alias="filterWakeupWord")
    """
    Filter wakeup words from results.
    """
    result_type: ResultType | None = Field(default=None, alias="resultType")
    """
    Type of results to return.
    """
    no_input_timeout_ms: float | None = Field(default=None, alias="noInputTimeoutMs")
    """
    Timeout in milliseconds before no-input event.
    """
    recognition_timeout_ms: float | None = Field(default=None, alias="recognitionTimeoutMs")
    """
    Maximum recognition duration in milliseconds.
    """
    utterance_end_silence_ms: float | None = Field(default=None, alias="utteranceEndSilenceMs")
    """
    Silence duration in milliseconds to detect end of utterance.
    """
    max_hypotheses: float | None = Field(default=None, alias="maxHypotheses")
    """
    Maximum number of recognition hypotheses to return.
    """
    speech_domain: str | None = Field(default=None, alias="speechDomain")
    """
    Speech domain for optimized recognition.
    """
    formatting: Formatting | None = None
    """
    Formatting options for recognition results.
    """
    client_data: dict[str, Any] | None = Field(default=None, alias="clientData")
    """
    Custom client data to pass to Nuance.
    """
    user_id: str | None = Field(default=None, alias="userId")
    """
    User ID for speaker adaptation.
    """
    speech_detection_sensitivity: float | None = Field(
        default=None, alias="speechDetectionSensitivity"
    )
    """
    Speech detection sensitivity (0-1).
    """
    resources: list[Resource] | None = None
    """
    Array of Nuance recognition resources (grammars, wordsets, etc.).
    """
