# generated by datamodel-codegen:
#   filename:  components/recognizer-houndifyOptions
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel


class HoundifyRecognizerOptions(JambonzModel):
    """
    Houndify-specific STT options. Only applies when recognizer vendor is 'houndify'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    request_info: dict[str, Any] | None = Field(default=None, alias="requestInfo")
    """
    Houndify RequestInfo object with context data.
    """
    sample_rate: float | None = Field(default=None, alias="sampleRate")
    """
    Audio sample rate in Hz.
    """
    latitude: float | None = None
    """
    User latitude for location-aware queries.
    """
    longitude: float | None = None
    """
    User longitude for location-aware queries.
    """
    city: str | None = None
    """
    User city.
    """
    state: str | None = None
    """
    User state.
    """
    country: str | None = None
    """
    User country.
    """
    time_zone: str | None = Field(default=None, alias="timeZone")
    """
    User timezone.
    """
    domain: str | None = None
    """
    Houndify domain.
    """
    audio_endpoint: str | None = Field(default=None, alias="audioEndpoint")
    """
    Custom audio endpoint URL.
    """
    max_silence_seconds: float | None = Field(default=None, alias="maxSilenceSeconds")
    """
    Maximum silence before stopping.
    """
    max_silence_after_full_query_seconds: float | None = Field(
        default=None, alias="maxSilenceAfterFullQuerySeconds"
    )
    """
    Silence timeout after a complete query.
    """
    max_silence_after_partial_query_seconds: float | None = Field(
        default=None, alias="maxSilenceAfterPartialQuerySeconds"
    )
    """
    Silence timeout after a partial query.
    """
    vad_sensitivity: float | None = Field(default=None, alias="vadSensitivity")
    """
    VAD sensitivity level.
    """
    vad_timeout: float | None = Field(default=None, alias="vadTimeout")
    """
    VAD timeout in milliseconds.
    """
    vad_mode: str | None = Field(default=None, alias="vadMode")
    """
    VAD mode.
    """
    vad_voice_ms: float | None = Field(default=None, alias="vadVoiceMs")
    """
    Milliseconds of voice to trigger VAD.
    """
    vad_silence_ms: float | None = Field(default=None, alias="vadSilenceMs")
    """
    Milliseconds of silence to trigger VAD.
    """
    vad_debug: bool | None = Field(default=None, alias="vadDebug")
    """
    Enable VAD debug logging.
    """
    audio_format: str | None = Field(default=None, alias="audioFormat")
    """
    Audio format.
    """
    enable_noise_reduction: bool | None = Field(default=None, alias="enableNoiseReduction")
    """
    Enable noise reduction.
    """
    enable_profanity_filter: bool | None = Field(default=None, alias="enableProfanityFilter")
    """
    Filter profanity.
    """
    enable_punctuation: bool | None = Field(default=None, alias="enablePunctuation")
    """
    Enable punctuation.
    """
    enable_capitalization: bool | None = Field(default=None, alias="enableCapitalization")
    """
    Enable capitalization.
    """
    confidence_threshold: float | None = Field(default=None, alias="confidenceThreshold")
    """
    Minimum confidence threshold.
    """
    enable_disfluency_filter: bool | None = Field(default=None, alias="enableDisfluencyFilter")
    """
    Filter disfluencies (um, uh).
    """
    max_results: float | None = Field(default=None, alias="maxResults")
    """
    Maximum number of results.
    """
    enable_word_timestamps: bool | None = Field(default=None, alias="enableWordTimestamps")
    """
    Include word timestamps.
    """
    max_alternatives: float | None = Field(default=None, alias="maxAlternatives")
    """
    Maximum alternative transcripts.
    """
    partial_transcript_interval: float | None = Field(
        default=None, alias="partialTranscriptInterval"
    )
    """
    Interval for partial transcript delivery.
    """
    session_timeout: float | None = Field(default=None, alias="sessionTimeout")
    """
    Session timeout.
    """
    connection_timeout: float | None = Field(default=None, alias="connectionTimeout")
    """
    Connection timeout.
    """
    custom_vocabulary: list[str] | None = Field(default=None, alias="customVocabulary")
    """
    Custom vocabulary terms.
    """
    language_model: str | None = Field(default=None, alias="languageModel")
    """
    Language model to use.
    """
    audio_query_absolute_timeout: float | None = Field(
        default=None, alias="audioQueryAbsoluteTimeout"
    )
    """
    Absolute timeout for audio queries.
    """
