# generated by datamodel-codegen:
#   filename:  components/synthesizer
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel


class Engine(Enum):
    """
    The synthesis engine tier to use. Availability depends on the vendor.
    """

    standard = "standard"
    neural = "neural"
    generative = "generative"
    long_form = "long-form"


class Gender(Enum):
    """
    Preferred voice gender. Used by some vendors (e.g. Google) when a specific voice is not specified.
    """

    male = "MALE"
    female = "FEMALE"
    neutral = "NEUTRAL"


class Synthesizer(JambonzModel):
    """
    Configuration for text-to-speech synthesis. Specifies the TTS vendor, voice, language, and vendor-specific options. Can be set at the session level via the 'config' verb or overridden per-verb (e.g. on 'say').
    """

    vendor: str = Field(
        ...,
        examples=[
            "google",
            "aws",
            "microsoft",
            "elevenlabs",
            "cartesia",
            "deepgram",
            "ibm",
            "nuance",
            "nvidia",
            "wellsaid",
            "whisper",
            "verbio",
            "custom",
        ],
    )
    """
    The TTS vendor to use. Must match a vendor configured in the jambonz platform.
    """
    label: str | None = None
    """
    An optional label identifying a specific credential set for this vendor. Used when multiple credentials are configured for the same vendor on the jambonz platform.
    """
    language: str | None = Field(
        default=None, examples=["en-US", "en-GB", "es-ES", "fr-FR", "de-DE"]
    )
    """
    The language code for speech synthesis, in BCP-47 format.
    """
    voice: str | dict[str, Any] | None = Field(
        default=None, examples=["en-US-Wavenet-D", "Joanna", "EXAVITQu4vr4xnSDxMaL"]
    )
    """
    The voice to use for synthesis. Format varies by vendor: Google uses voice names like 'en-US-Wavenet-D', AWS Polly uses names like 'Joanna', but ElevenLabs and Cartesia require voice IDs (alphanumeric strings like 'EXAVITQu4vr4xnSDxMaL'), not human-readable names. Some vendors accept an object for more complex voice configuration.
    """
    fallback_vendor: str | None = Field(default=None, alias="fallbackVendor")
    """
    A backup TTS vendor to use if the primary vendor fails or is unavailable.
    """
    fallback_label: str | None = Field(default=None, alias="fallbackLabel")
    """
    Credential label for the fallback vendor.
    """
    fallback_language: str | None = Field(default=None, alias="fallbackLanguage")
    """
    Language code to use with the fallback vendor.
    """
    fallback_voice: str | dict[str, Any] | None = Field(default=None, alias="fallbackVoice")
    """
    Voice to use with the fallback vendor.
    """
    engine: Engine | None = None
    """
    The synthesis engine tier to use. Availability depends on the vendor.
    """
    gender: Gender | None = None
    """
    Preferred voice gender. Used by some vendors (e.g. Google) when a specific voice is not specified.
    """
    options: dict[str, Any] | None = None
    """
    Vendor-specific options passed through to the TTS provider. The structure depends on the vendor being used.
    """
