# generated by datamodel-codegen:
#   filename:  components/target
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel

from . import actionHook
from . import auth as auth_1


class Type(Enum):
    """
    The type of target to dial.
    """

    phone = "phone"
    sip = "sip"
    user = "user"
    teams = "teams"


class Method(Enum):
    """
    The HTTP method to use when invoking the confirmHook.
    """

    get = "GET"
    post = "POST"


class From(JambonzModel):
    """
    Override the From header on the outbound SIP INVITE.
    """

    user: str | None = None
    """
    The user part of the SIP From URI.
    """
    host: str | None = None
    """
    The host part of the SIP From URI.
    """


class Target(JambonzModel):
    """
    A call target for the 'dial' verb. Specifies who or what to connect the call to: a phone number (PSTN), a SIP endpoint, a registered user, or a Microsoft Teams user.
    """

    type: Type
    """
    The type of target to dial.
    """
    number: str | None = Field(default=None, examples=["+15085551212"])
    """
    The phone number to dial. Required when type is 'phone'. Use E.164 format.
    """
    sip_uri: str | None = Field(default=None, alias="sipUri", examples=["sip:alice@example.com"])
    """
    The SIP URI to dial. Required when type is 'sip'.
    """
    name: str | None = None
    """
    The registered user name to dial. Required when type is 'user'. Also used as the display name for SIP targets.
    """
    tenant: str | None = None
    """
    The Microsoft Teams tenant ID. Required when type is 'teams'.
    """
    trunk: str | None = None
    """
    The SIP trunk to use for the outbound call. When specified, overrides the default carrier routing.
    """
    confirm_hook: str | actionHook.ActionHook | None = Field(default=None, alias="confirmHook")
    """
    A webhook to invoke when the target answers, before connecting the call. Use this to screen calls, play a whisper prompt, or require the target to press a key to accept.
    """
    method: Method | None = "POST"
    """
    The HTTP method to use when invoking the confirmHook.
    """
    headers: dict[str, str] | None = None
    """
    Custom SIP headers to include on the outbound INVITE. Keys are header names, values are header values.
    """
    from_: From | None = Field(default=None, alias="from")
    """
    Override the From header on the outbound SIP INVITE.
    """
    auth: auth_1.Auth | None = None
    """
    SIP authentication credentials for the outbound call, if the far end requires digest auth.
    """
    vmail: bool | None = None
    """
    If true, follow the call into voicemail if the target does not answer.
    """
    override_to: str | None = Field(default=None, alias="overrideTo")
    """
    Override the Request-URI on the outbound SIP INVITE. Useful when the Request-URI needs to differ from the To header.
    """
    proxy: str | None = Field(default=None, examples=["sip:proxy.example.com"])
    """
    A SIP proxy to route the outbound call through, specified as a SIP URI.
    """
