# generated by datamodel-codegen:
#   filename:  components/vad
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import Field, confloat
from jambonz_sdk._models.base import JambonzModel


class Vendor(Enum):
    """
    The VAD engine to use.
    """

    webrtc = "webrtc"
    silero = "silero"


class VAD(JambonzModel):
    """
    Voice Activity Detection configuration. Controls how jambonz detects the presence or absence of speech on the audio channel. Used to determine speech start/end boundaries for recognition and barge-in.
    """

    enable: bool | None = None
    """
    Whether to enable voice activity detection.
    """
    voice_ms: float | None = Field(default=None, alias="voiceMs", examples=[250])
    """
    Duration of voice activity (in milliseconds) required before speech is considered to have started.
    """
    silence_ms: float | None = Field(default=None, alias="silenceMs", examples=[1000])
    """
    Duration of silence (in milliseconds) required before speech is considered to have ended.
    """
    strategy: str | None = None
    """
    The VAD strategy to use.
    """
    mode: confloat(ge=0.0, le=3.0) | None = None
    """
    WebRTC VAD aggressiveness mode (0-3). Higher values are more aggressive at filtering non-speech. Only applies when vendor is 'webrtc'.
    """
    vendor: Vendor | None = None
    """
    The VAD engine to use.
    """
    threshold: confloat(ge=0.0, le=1.0) | None = None
    """
    Speech detection confidence threshold for Silero VAD. Value between 0 and 1, where higher values require greater confidence. Only applies when vendor is 'silero'.
    """
    speech_pad_ms: float | None = Field(default=None, alias="speechPadMs")
    """
    Padding in milliseconds added before and after detected speech segments. Prevents clipping utterance boundaries. Only applies when vendor is 'silero'.
    """
