# generated by datamodel-codegen:
#   filename:  verbs/agent
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import ConfigDict, Field, confloat

from ..components import actionHook, recognizer, synthesizer
from jambonz_sdk._models.base import JambonzModel
from .llm import LLM


class TurnDetection(Enum):
    """
    Turn detection strategy shorthand. 'stt' uses the STT vendor's native signals (silence-based for most vendors; acoustic+semantic for deepgramflux, assemblyai, speechmatics). 'krisp' uses the Krisp acoustic end-of-turn model with default settings.
    """

    stt = "stt"
    krisp = "krisp"


class Mode(Enum):
    """
    Turn detection mode. Currently only 'krisp' supports object-form tuning.
    """

    krisp = "krisp"


class TurnDetection1(JambonzModel):
    """
    Turn detection configuration with tunable parameters.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Mode
    """
    Turn detection mode. Currently only 'krisp' supports object-form tuning.
    """
    threshold: confloat(ge=0.0, le=1.0) | None = None
    """
    Krisp end-of-turn confidence threshold (0.0–1.0). Lower values trigger earlier turn transitions. Default: 0.5
    """
    model: str | None = None
    """
    Optional Krisp model name override.
    """


class BargeIn(JambonzModel):
    """
    Controls whether and how the user can interrupt the assistant while it is speaking.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    enable: bool | None = True
    """
    Allow the user to interrupt the assistant while it is speaking. Default: true.
    """
    min_speech_duration: confloat(ge=0.0) | None = Field(default=0.5, alias="minSpeechDuration")
    """
    Seconds of detected speech required before confirming an interruption. Prevents brief noises from cutting off the assistant. Default: 0.5
    """
    sticky: bool | None = False
    """
    If true, once the user interrupts the assistant does not resume speaking. Default: false.
    """


class NoiseIsolation(Enum):
    """
    Shorthand — enable noise isolation with the specified vendor using default settings.
    """

    krisp = "krisp"
    rnnoise = "rnnoise"


class Direction(Enum):
    """
    Audio direction to apply noise isolation. 'read' filters caller audio, 'write' filters outbound audio. Default: 'read'.
    """

    read = "read"
    write = "write"


class NoiseIsolation1(JambonzModel):
    """
    Detailed noise isolation configuration.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mode: str
    """
    Noise isolation vendor/mode (e.g. 'krisp').
    """
    level: confloat(ge=0.0, le=100.0) | None = None
    """
    Suppression level 0–100. Default: 100.
    """
    direction: Direction | None = None
    """
    Audio direction to apply noise isolation. 'read' filters caller audio, 'write' filters outbound audio. Default: 'read'.
    """
    model: str | None = None
    """
    Optional model name override.
    """


class McpServer(JambonzModel):
    url: str
    """
    The URL of the MCP server.
    """
    auth: dict[str, Any] | None = None
    """
    Authentication for the MCP server.
    """
    roots: list[dict[str, Any]] | None = None
    """
    MCP root definitions.
    """


class Agent(JambonzModel):
    """
    Configures a complete voice AI agent by wiring together STT → LLM → TTS with integrated turn detection. Provides a higher-level abstraction than manually orchestrating the individual components. Optimized for building voice AI agents with proper turn-taking behavior.
    """

    verb: Literal["agent"] = "agent"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    stt: recognizer.Recognizer | None = None
    """
    Speech-to-text configuration for the agent.
    """
    tts: synthesizer.Synthesizer | None = None
    """
    Text-to-speech configuration for the agent.
    """
    turn_detection: TurnDetection | TurnDetection1 | None = Field(
        default="stt", alias="turnDetection", validate_default=True
    )
    """
    Turn detection strategy. Controls when the agent decides the user has finished speaking. STT vendors with native turn-taking (deepgramflux, assemblyai, speechmatics) always use their built-in detection regardless of this setting.
    """
    barge_in: BargeIn | None = Field(default=None, alias="bargeIn")
    """
    Controls whether and how the user can interrupt the assistant while it is speaking.
    """
    no_response_timeout: confloat(ge=0.0) | None = Field(default=0, alias="noResponseTimeout")
    """
    Seconds to wait after the assistant finishes speaking before prompting the user to respond. 0 disables. Default: 0.
    """
    llm: LLM
    """
    LLM configuration for the agent. See the 'llm' verb schema for details.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the agent ends.
    """
    event_hook: actionHook.ActionHook | None = Field(default=None, alias="eventHook")
    """
    A webhook invoked for agent events. Receives event types: 'user_transcript' (user speech recognized), 'llm_response' (assistant reply), 'user_interruption' (barge-in detected), and 'turn_end' (end-of-turn summary with transcript, response, and latency metrics).
    """
    tool_hook: actionHook.ActionHook | None = Field(default=None, alias="toolHook")
    """
    A webhook invoked when the LLM requests a tool/function call. The payload includes the tool name and arguments; the response provides the tool result.
    """
    greeting: bool | None = True
    """
    Whether the LLM should generate an initial greeting before the user speaks. Default: true.
    """
    early_generation: bool | None = Field(default=False, alias="earlyGeneration")
    """
    Enable speculative LLM prompting before end-of-turn is confirmed. When using Krisp turn detection, set this to true to speculatively prompt the LLM before Krisp confirms the turn has ended. If the transcript matches when turn ends, buffered tokens are released immediately — reducing response latency. Note: Deepgram Flux performs early generation automatically via its native EagerEndOfTurn signal regardless of this setting. Default: false.
    """
    noise_isolation: NoiseIsolation | NoiseIsolation1 | None = Field(
        default=None, alias="noiseIsolation"
    )
    """
    Enable server-side noise isolation to reduce background noise on call audio. Defaults to filtering inbound (caller) audio; set direction to 'write' for outbound. Useful for improving STT accuracy in noisy environments.
    """
    mcp_servers: list[McpServer] | None = Field(default=None, alias="mcpServers")
    """
    External MCP servers that provide tools to the LLM. The agent connects at startup via SSE, discovers available tools, and makes them callable by the LLM.
    """
