# generated by datamodel-codegen:
#   filename:  verbs/alert
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel


class Alert(JambonzModel):
    """
    Sends a 180 Ringing provisional response with an Alert-Info header. Used to trigger a specific ring tone or alert behavior on the caller's device before the call is answered.
    """

    verb: Literal["alert"] = "alert"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    message: str = Field(..., examples=["info=alert-internal", "http://example.com/ringtone.wav"])
    """
    The value to include in the Alert-Info header.
    """
