# generated by datamodel-codegen:
#   filename:  verbs/answer
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Literal
from jambonz_sdk._models.base import JambonzModel


class Answer(JambonzModel):
    """
    Answers an incoming call (sends a 200 OK to the SIP INVITE). Most verbs implicitly answer the call, so this verb is only needed when you want to explicitly control when the call is answered — for example, to play early media before answering.
    """

    verb: Literal["answer"] = "answer"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
