# generated by datamodel-codegen:
#   filename:  verbs/config
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import Field

from ..components import actionHook, actionHookDelayAction
from ..components import amd as amd_1
from ..components import fillerNoise
from ..components import recognizer as recognizer_1
from ..components import synthesizer as synthesizer_1
from ..components import vad as vad_1
from jambonz_sdk._models.base import JambonzModel


class InputEnum(Enum):
    speech = "speech"
    digits = "digits"


class NoiseIsolation(JambonzModel):
    """
    Noise isolation configuration to reduce background noise on call audio. Defaults to filtering inbound (caller) audio; can also filter outbound audio via the direction option.
    """

    enable: bool | None = None
    vendor: str | None = None
    level: float | None = None
    model: str | None = None


class TurnTaking(JambonzModel):
    """
    Turn-taking detection configuration for conversational AI applications.
    """

    enable: bool | None = None
    vendor: str | None = None
    threshold: float | None = None
    model: str | None = None


class BargeIn(JambonzModel):
    """
    Default barge-in configuration. When enabled, callers can interrupt playing prompts with speech or DTMF.
    """

    enable: bool | None = None
    sticky: bool | None = None
    """
    If true, barge-in settings persist across verbs rather than resetting after each verb.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    input: list[InputEnum] | None = None
    min_bargein_word_count: float | None = Field(default=None, alias="minBargeinWordCount")


class TtsStream(JambonzModel):
    """
    Default TTS streaming configuration for the session.
    """

    enable: bool | None = None
    synthesizer: synthesizer_1.Synthesizer | None = None


class Config(JambonzModel):
    """
    Sets session-level defaults for the call. Configures default TTS, STT, VAD, recording, streaming, and other session-wide settings. These defaults apply to all subsequent verbs unless overridden at the verb level. Typically the first verb in an application. Can be used multiple times during a call to change settings.
    """

    verb: Literal["config"] = "config"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    synthesizer: synthesizer_1.Synthesizer | None = None
    """
    Default TTS configuration for the session.
    """
    recognizer: recognizer_1.Recognizer | None = None
    """
    Default STT configuration for the session.
    """
    barge_in: BargeIn | None = Field(default=None, alias="bargeIn")
    """
    Default barge-in configuration. When enabled, callers can interrupt playing prompts with speech or DTMF.
    """
    tts_stream: TtsStream | None = Field(default=None, alias="ttsStream")
    """
    Default TTS streaming configuration for the session.
    """
    record: dict[str, Any] | None = None
    """
    Session-level call recording configuration.
    """
    listen: dict[str, Any] | None = None
    """
    Session-level audio streaming configuration defaults. Properties match the listen verb but no fields are required here.
    """
    stream: dict[str, Any] | None = None
    """
    Session-level audio streaming configuration defaults. Alias for 'listen'.
    """
    transcribe: dict[str, Any] | None = None
    """
    Session-level transcription configuration defaults.
    """
    amd: amd_1.AnsweringMachineDetection | None = None
    """
    Session-level answering machine detection configuration.
    """
    filler_noise: fillerNoise.FillerNoise | None = Field(default=None, alias="fillerNoise")
    """
    Default filler noise configuration for the session.
    """
    vad: vad_1.VAD | None = None
    """
    Default voice activity detection configuration for the session.
    """
    notify_events: bool | None = Field(default=None, alias="notifyEvents")
    """
    If true, send call events (e.g. DTMF, call status changes) to the application via the status webhook.
    """
    notify_stt_latency: bool | None = Field(default=None, alias="notifySttLatency")
    """
    If true, include STT latency measurements in webhook payloads.
    """
    reset: str | list[str] | None = None
    """
    Reset specific session-level settings to their defaults. Pass a setting name or array of setting names to reset.
    """
    on_hold_music: str | None = Field(default=None, alias="onHoldMusic")
    """
    URL of an audio file to play when the call is placed on hold.
    """
    action_hook_delay_action: actionHookDelayAction.ActionHookDelayAction | None = Field(
        default=None, alias="actionHookDelayAction"
    )
    """
    Default configuration for handling slow webhook responses.
    """
    sip_request_within_dialog_hook: actionHook.ActionHook | None = Field(
        default=None, alias="sipRequestWithinDialogHook"
    )
    """
    A webhook to invoke when a SIP request (e.g. INFO, NOTIFY) is received within the dialog.
    """
    boost_audio_signal: float | str | None = Field(default=None, alias="boostAudioSignal")
    """
    Boost (or attenuate) the audio signal in dB for the session.
    """
    refer_hook: actionHook.ActionHook | None = Field(default=None, alias="referHook")
    """
    A webhook to invoke when a SIP REFER request is received.
    """
    early_media: bool | None = Field(default=None, alias="earlyMedia")
    """
    If true, allow early media (audio before call answer) for the session.
    """
    auto_stream_tts: bool | None = Field(default=None, alias="autoStreamTts")
    """
    If true, automatically use streaming TTS for all 'say' verbs in the session.
    """
    disable_tts_cache: bool | None = Field(default=None, alias="disableTtsCache")
    """
    If true, disable TTS caching for the session.
    """
    track_tts_playout: bool | None = Field(default=None, alias="trackTtsPlayout")
    """
    If true, report the actual text spoken via TTS. Requires a TTS vendor that supports alignment data (e.g. ElevenLabs). On each utterance completion or interruption, a tts_spoken event is sent to the '/streaming-event' endpoint with fields: 'text' (string — the text actually spoken) and 'bargein' (boolean — true if the user interrupted before TTS finished). See the tts-streaming-event callback schema for full details.
    """
    noise_isolation: NoiseIsolation | None = Field(default=None, alias="noiseIsolation")
    """
    Noise isolation configuration to reduce background noise on call audio. Defaults to filtering inbound (caller) audio; can also filter outbound audio via the direction option.
    """
    turn_taking: TurnTaking | None = Field(default=None, alias="turnTaking")
    """
    Turn-taking detection configuration for conversational AI applications.
    """
