# generated by datamodel-codegen:
#   filename:  verbs/conference
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from ..components import actionHook
from jambonz_sdk._models.base import JambonzModel


class Conference(JambonzModel):
    """
    Places the caller into a multi-party conference room. Multiple callers in the same named conference can speak to each other. Supports features like muting, recording, waiting rooms, and participant limits.
    """

    verb: Literal["conference"] = "conference"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    name: str = Field(..., examples=["team-standup", "customer-call-12345"])
    """
    The name of the conference room. All callers joining the same named conference are connected together.
    """
    beep: bool | None = None
    """
    If true, play a beep when participants join or leave.
    """
    member_tag: str | None = Field(default=None, alias="memberTag")
    """
    A tag to identify this participant. Can be used to target specific members for actions like muting or whispering.
    """
    speak_only_to: str | None = Field(default=None, alias="speakOnlyTo")
    """
    If set, this participant's audio is only heard by the member with the specified memberTag. Creates a private whisper channel.
    """
    start_conference_on_enter: bool | None = Field(default=None, alias="startConferenceOnEnter")
    """
    If true (default), the conference starts when this participant joins. If false, this participant waits silently until a participant with startConferenceOnEnter=true joins.
    """
    end_conference_on_exit: bool | None = Field(default=None, alias="endConferenceOnExit")
    """
    If true, the conference ends for all participants when this participant leaves.
    """
    end_conference_duration: float | None = Field(default=None, alias="endConferenceDuration")
    """
    Maximum duration of the conference in seconds.
    """
    max_participants: float | None = Field(default=None, alias="maxParticipants")
    """
    Maximum number of participants allowed in the conference.
    """
    join_muted: bool | None = Field(default=None, alias="joinMuted")
    """
    If true, this participant joins the conference muted.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when this participant leaves the conference.
    """
    wait_hook: actionHook.ActionHook | None = Field(default=None, alias="waitHook")
    """
    A webhook invoked while this participant is waiting for the conference to start. Should return verbs to play (e.g. hold music).
    """
    status_events: list[str] | None = Field(default=None, alias="statusEvents")
    """
    List of conference events to receive via the statusHook.
    """
    status_hook: actionHook.ActionHook | None = Field(default=None, alias="statusHook")
    """
    A webhook to receive conference status events (joins, leaves, etc.).
    """
    enter_hook: actionHook.ActionHook | None = Field(default=None, alias="enterHook")
    """
    A webhook invoked when this participant first enters the conference.
    """
    record: dict[str, Any] | None = None
    """
    Recording configuration for the conference.
    """
    listen: dict[str, Any] | None = None
    """
    Audio streaming configuration for the conference.
    """
    distribute_dtmf: bool | None = Field(default=None, alias="distributeDtmf")
    """
    If true, DTMF events from this participant are distributed to all other participants.
    """
