# generated by datamodel-codegen:
#   filename:  verbs/deepgram_s2s
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from ..components.llm_base import LlmBaseProperties


class DeepgramS2S(LlmBaseProperties):
    """
    Shortcut for 'llm' with vendor automatically set to 'deepgram'. Connects the caller to a Deepgram model for real-time speech-to-speech voice conversation.
    """

    verb: Literal["deepgram_s2s"] = "deepgram_s2s"
    """
    The verb name.
    """
    vendor: Literal["deepgram"] = "deepgram"
    """
    The LLM vendor (always 'deepgram' for this shortcut).
    """
    llm_options: dict[str, Any] = Field(
        ...,
        alias="llmOptions",
        examples=[
            {
                "Settings": {
                    "agent": {
                        "think": {
                            "provider": {"type": "open_ai", "model": "gpt-4o"},
                            "prompt": "You are a helpful voice assistant.",
                        },
                        "speak": {
                            "provider": {
                                "type": "deepgram",
                                "model": "aura-2-thalia-en",
                            }
                        },
                    }
                }
            }
        ],
    )
    """
    IMPORTANT: Deepgram does NOT use a 'messages' array. The llmOptions must contain a 'Settings' object with 'agent.think' (LLM provider, model, and prompt) and 'agent.speak' (TTS provider and voice model). The system prompt goes in Settings.agent.think.prompt, NOT in messages.
    """
