# generated by datamodel-codegen:
#   filename:  verbs/dequeue
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel

from ..components import actionHook


class Dequeue(JambonzModel):
    """
    Removes a caller from a named queue and bridges them to the current call. Typically used by an agent or operator call flow to connect with the next waiting caller.
    """

    verb: Literal["dequeue"] = "dequeue"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    name: str = Field(..., examples=["support", "sales"])
    """
    The name of the queue to dequeue from.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the dequeued call ends.
    """
    timeout: float | None = None
    """
    Time in seconds to wait for a caller to be available in the queue.
    """
    beep: bool | None = None
    """
    If true, play a beep when the calls are connected.
    """
    call_sid: str | None = Field(default=None, alias="callSid")
    """
    Dequeue a specific call by its call SID, rather than the next caller in line.
    """
