# generated by datamodel-codegen:
#   filename:  verbs/dialogflow
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import ConfigDict, Field

from jambonz_sdk._models.base import JambonzModel

from ..components import actionHook, synthesizer


class Model(Enum):
    """
    The Dialogflow model type: 'es' for Dialogflow ES, 'cx' for Dialogflow CX, 'ces' for Dialogflow CES.
    """

    es = "es"
    cx = "cx"
    ces = "ces"


class QueryInput(JambonzModel):
    """
    Initial query input to send to Dialogflow.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    text: str | None = None
    """
    Text input.
    """
    intent: str | None = None
    """
    Intent to trigger.
    """
    event: str | None = None
    """
    Event to trigger.
    """
    dtmf: str | None = None
    """
    DTMF input.
    """


class Dialogflow(JambonzModel):
    """
    Connects the caller to a Google Dialogflow agent for a voice conversation. Supports Dialogflow ES, CX, and CES models. The caller speaks and Dialogflow handles intent detection and response generation.
    """

    verb: Literal["dialogflow"] = "dialogflow"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    credentials: dict[str, Any] | str
    """
    Google service account credentials as a JSON object or stringified JSON.
    """
    project: str
    """
    The Google Cloud project ID.
    """
    agent: str | None = None
    """
    The Dialogflow agent ID. Required for CX agents.
    """
    environment: str | None = None
    """
    The Dialogflow environment to use.
    """
    region: str | None = None
    """
    The Google Cloud region for the Dialogflow API endpoint.
    """
    model: Model | None = None
    """
    The Dialogflow model type: 'es' for Dialogflow ES, 'cx' for Dialogflow CX, 'ces' for Dialogflow CES.
    """
    lang: str
    """
    The language code for the conversation (e.g. 'en-US').
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the Dialogflow session ends.
    """
    event_hook: actionHook.ActionHook | None = Field(default=None, alias="eventHook")
    """
    A webhook invoked for Dialogflow events during the conversation.
    """
    events: list[str] | None = None
    """
    List of event types to receive via the eventHook.
    """
    welcome_event: str | None = Field(default=None, alias="welcomeEvent")
    """
    A Dialogflow event to trigger at the start of the conversation (e.g. 'welcome').
    """
    welcome_event_params: dict[str, Any] | None = Field(default=None, alias="welcomeEventParams")
    """
    Parameters to pass with the welcome event.
    """
    no_input_timeout: float | None = Field(default=None, alias="noInputTimeout")
    """
    Seconds to wait for caller input before triggering the no-input event.
    """
    no_input_event: str | None = Field(default=None, alias="noInputEvent")
    """
    Dialogflow event to trigger when no input is received within the timeout.
    """
    pass_dtmf_as_text_input: bool | None = Field(default=None, alias="passDtmfAsTextInput")
    """
    If true, pass DTMF digits to Dialogflow as text input.
    """
    thinking_music: str | None = Field(default=None, alias="thinkingMusic")
    """
    URL of an audio file to play while waiting for Dialogflow to respond.
    """
    tts: synthesizer.Synthesizer | None = None
    """
    TTS configuration for Dialogflow responses.
    """
    bargein: bool | None = None
    """
    If true, allow the caller to interrupt Dialogflow responses with speech.
    """
    query_input: QueryInput | None = Field(default=None, alias="queryInput")
    """
    Initial query input to send to Dialogflow.
    """
