# generated by datamodel-codegen:
#   filename:  verbs/dial
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel

from ..components import actionHook
from ..components import amd as amd_1
from ..components import target as target_1
from . import dub as dub_1


class Dial(JambonzModel):
    """
    Initiates an outbound call to one or more targets and bridges the caller to the first target that answers. Targets can be phone numbers (PSTN), SIP endpoints, registered users, or Microsoft Teams users. Supports simultaneous ringing, call screening, recording, and DTMF capture during the bridged call.
    """

    verb: Literal["dial"] = "dial"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    target: list[target_1.Target] = Field(..., min_length=1)
    """
    One or more call targets to dial. If multiple targets are specified, they are rung simultaneously and the first to answer is connected. The rest are canceled.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the dialed call ends. Receives call disposition details (duration, who hung up, etc.) and should return the next verbs to execute.
    """
    on_hold_hook: actionHook.ActionHook | None = Field(default=None, alias="onHoldHook")
    """
    A webhook invoked when the call is placed on hold. Should return verbs to execute (e.g. play hold music) while the caller is holding.
    """
    answer_on_bridge: bool | None = Field(default=None, alias="answerOnBridge")
    """
    If true, delay answering the inbound call until the outbound leg is answered. This allows the caller to hear ringing until the target picks up, and avoids billing the caller for unanswered outbound attempts.
    """
    caller_id: str | None = Field(default=None, alias="callerId", examples=["+15085551212"])
    """
    The caller ID (phone number) to present on the outbound call. Overrides the default caller ID.
    """
    caller_name: str | None = Field(default=None, alias="callerName")
    """
    The caller display name to present on the outbound call.
    """
    confirm_hook: actionHook.ActionHook | None = Field(default=None, alias="confirmHook")
    """
    A webhook invoked when a target answers, before the call is bridged. Used for call screening — the webhook can return verbs (e.g. a 'say' prompt and 'gather') to confirm the callee wants to accept the call.
    """
    refer_hook: actionHook.ActionHook | None = Field(default=None, alias="referHook")
    """
    A webhook invoked when a SIP REFER is received on the bridged call. Allows handling call transfers initiated by the far end.
    """
    dial_music: str | None = Field(default=None, alias="dialMusic")
    """
    URL of an audio file to play to the caller while the outbound call is ringing. Replaces the default ringback tone.
    """
    dtmf_capture: list[str] | dict[str, Any] | None = Field(default=None, alias="dtmfCapture")
    """
    Configuration for capturing DTMF digits during the bridged call. Can be a simple array of patterns (applied to both legs) or an object with childCall/parentCall arrays.
    """
    dtmf_hook: actionHook.ActionHook | None = Field(default=None, alias="dtmfHook")
    """
    A webhook invoked when a captured DTMF pattern is detected during the bridged call.
    """
    headers: dict[str, str | float] | None = None
    """
    Custom SIP headers to include on the outbound INVITE.
    """
    anchor_media: bool | None = Field(default=None, alias="anchorMedia")
    """
    If true, keep media anchored through the jambonz media server even if a direct media path is possible. Required for features like recording, listen, and DTMF capture during bridged calls.
    """
    exit_media_path: bool | None = Field(default=None, alias="exitMediaPath")
    """
    If true, remove jambonz from the media path after the call is bridged. Reduces latency but disables mid-call features like recording and DTMF capture.
    """
    boost_audio_signal: float | str | None = Field(
        default=None, alias="boostAudioSignal", examples=[6, -3]
    )
    """
    Boost (or attenuate) the audio signal in dB. Positive values increase volume, negative values decrease it.
    """
    listen: dict[str, Any] | None = None
    """
    Nested listen configuration for streaming audio of the bridged call.
    """
    stream: dict[str, Any] | None = None
    """
    Nested stream configuration for streaming audio of the bridged call. Alias for 'listen'.
    """
    transcribe: dict[str, Any] | None = None
    """
    Nested transcribe configuration for real-time transcription of the bridged call.
    """
    time_limit: float | None = Field(default=None, alias="timeLimit", examples=[3600])
    """
    Maximum duration in seconds for the bridged call. The call is automatically hung up when this limit is reached.
    """
    timeout: float | None = Field(default=None, examples=[30, 60])
    """
    Time in seconds to wait for the target to answer before giving up.
    """
    proxy: str | None = Field(default=None, examples=["sip:proxy.example.com"])
    """
    A SIP proxy to route the outbound call through.
    """
    amd: amd_1.AnsweringMachineDetection | None = None
    """
    Answering machine detection configuration. When enabled, jambonz attempts to determine whether the call was answered by a human or a machine.
    """
    dub: list[dub_1.Dub] | None = None
    """
    Nested dub verbs — audio dubbing configuration for mixing additional audio tracks into the bridged call.
    """
    tag: dict[str, Any] | None = None
    """
    Arbitrary metadata to attach to this call leg. Included in subsequent webhook invocations and CDRs.
    """
    forward_pai: bool | None = Field(default=None, alias="forwardPAI")
    """
    If true, forward the P-Asserted-Identity header from the inbound call to the outbound call.
    """
