# generated by datamodel-codegen:
#   filename:  verbs/dtmf
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel


class DTMF(JambonzModel):
    """
    Sends DTMF tones on the call. Used to interact with IVR systems on the far end, or to signal systems that respond to DTMF.
    """

    verb: Literal["dtmf"] = "dtmf"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    dtmf: str = Field(..., examples=["1234#", "1w2w3", "5551212"])
    """
    The DTMF digits to send. Valid characters are 0-9, *, #, and A-D. Use 'w' for a 500ms pause between digits.
    """
    duration: float | None = Field(default=500, examples=[250, 500])
    """
    Duration in milliseconds for each DTMF tone.
    """
