# generated by datamodel-codegen:
#   filename:  verbs/dub
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import Field
from jambonz_sdk._models.base import JambonzModel


class Action(Enum):
    """
    The dubbing action to perform.
    """

    add_track = "addTrack"
    remove_track = "removeTrack"
    silence_track = "silenceTrack"
    play_on_track = "playOnTrack"
    say_on_track = "sayOnTrack"


class Dub(JambonzModel):
    """
    Manages audio dubbing tracks on a call. Allows adding, removing, and controlling auxiliary audio tracks that are mixed into the call audio. Used for background music, coaching whispers, or injecting audio from external sources.
    """

    verb: Literal["dub"] = "dub"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    action: Action
    """
    The dubbing action to perform.
    """
    track: str = Field(..., examples=["background-music", "coach-whisper"])
    """
    The name of the audio track. Used to reference the track in subsequent dub actions.
    """
    play: str | None = None
    """
    URL of an audio file to play on the track. Used with 'playOnTrack' action.
    """
    say: str | dict[str, Any] | None = None
    """
    Text to synthesize and play on the track. Used with 'sayOnTrack' action. Can be a string or a say configuration object.
    """
    loop: bool | None = None
    """
    If true, loop the audio on the track continuously.
    """
    gain: float | str | None = Field(default=None, examples=[-10, 0, 6])
    """
    Audio gain for the track in dB. Use negative values to reduce volume.
    """
