# generated by datamodel-codegen:
#   filename:  verbs/elevenlabs_s2s
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import ConfigDict, Field

from ..components.llm_base import LlmBaseProperties
from jambonz_sdk._models.base import JambonzModel


class Auth(JambonzModel):
    """
    Authentication credentials for ElevenLabs. Requires agent_id; api_key is optional (if not provided, an unsigned URL is used).
    """

    agent_id: str
    """
    The ElevenLabs Conversational AI agent ID. Required.
    """
    api_key: str | None = None
    """
    The ElevenLabs API key. Optional; when provided, a signed URL is used for the WebSocket connection.
    """


class LlmOptions(JambonzModel):
    """
    Options for the ElevenLabs conversation session.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    conversation_initiation_client_data: dict[str, Any] | None = None
    """
    Optional data sent to the agent when the conversation starts.
    """
    input_sample_rate: int | None = 16000
    """
    Audio input sample rate in Hz.
    """
    output_sample_rate: int | None = 16000
    """
    Audio output sample rate in Hz.
    """


class ElevenlabsS2S(LlmBaseProperties):
    """
    Shortcut for 'llm' with vendor automatically set to 'elevenlabs'. Connects the caller to an ElevenLabs Conversational AI agent for real-time speech-to-speech voice conversation. Unlike other s2s vendors, ElevenLabs requires a pre-configured agent_id rather than a model and messages.
    """

    verb: Literal["elevenlabs_s2s"] = "elevenlabs_s2s"
    """
    The verb name.
    """
    vendor: Literal["elevenlabs"] = "elevenlabs"
    """
    The LLM vendor (always 'elevenlabs' for this shortcut).
    """
    auth: Auth
    """
    Authentication credentials for ElevenLabs. Requires agent_id; api_key is optional (if not provided, an unsigned URL is used).
    """
    llm_options: LlmOptions | None = Field(default=None, alias="llmOptions")
    """
    Options for the ElevenLabs conversation session.
    """
