# generated by datamodel-codegen:
#   filename:  verbs/enqueue
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ..components import actionHook
from jambonz_sdk._models.base import JambonzModel


class Enqueue(JambonzModel):
    """
    Places the caller into a named call queue. While in the queue, the caller hears content returned by the waitHook (typically hold music or position announcements). The caller remains in the queue until dequeued by another call or process.
    """

    verb: Literal["enqueue"] = "enqueue"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    name: str = Field(..., examples=["support", "sales"])
    """
    The name of the queue to place the caller in. Queues are created implicitly when first referenced.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the caller leaves the queue (either dequeued or hung up). Should return the next verbs to execute.
    """
    wait_hook: actionHook.ActionHook | None = Field(default=None, alias="waitHook")
    """
    A webhook invoked immediately when the caller enters the queue and periodically while waiting. Should return verbs to play to the caller (e.g. hold music, queue position announcements).
    """
    priority: float | None = Field(default=None, examples=[1, 5, 10])
    """
    The priority of this caller in the queue. Lower numbers are higher priority and are dequeued first.
    """
