# generated by datamodel-codegen:
#   filename:  verbs/gather
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import Field, model_validator

from jambonz_sdk._models.base import JambonzModel

from ..components import actionHook, actionHookDelayAction, fillerNoise
from ..components import recognizer as recognizer_1
from .play import Play
from .say import Say


class InputEnum(Enum):
    speech = "speech"
    digits = "digits"


class Gather(JambonzModel):
    """
    Collects user input via speech (STT) and/or DTMF digits. Optionally plays a prompt (using nested 'say' or 'play') while listening. When input is received, the result is sent to the actionHook which should return the next set of verbs. This is the primary verb for building interactive voice menus and conversational flows.
    """

    verb: Literal["gather"] = "gather"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    Invoked when the gather completes. The payload includes 'reason' ('speechDetected', 'dtmfDetected', or 'timeout'), 'speech' (object with alternatives[].transcript and alternatives[].confidence when reason is speechDetected), and 'digits' (string when reason is dtmfDetected). In webhook mode this is a URL that receives an HTTP POST. In WebSocket mode this is an event name — use session.on('/hookName', (evt) => {...}) and respond with session.reply().
    """
    input: list[InputEnum] | None = Field(
        ["digits"], examples=[["speech", "digits"], ["speech"], ["digits"]]
    )
    """
    The types of input to accept. Can include 'speech' (STT), 'digits' (DTMF), or both.
    """
    finish_on_key: str | None = Field(default=None, alias="finishOnKey", examples=["#", "*"])
    """
    A DTMF key that signals the end of digit input. The key itself is not included in the collected digits.
    """
    num_digits: float | None = Field(default=None, alias="numDigits")
    """
    Exact number of DTMF digits to collect. Gather completes automatically when this many digits are received.
    """
    min_digits: float | None = Field(default=None, alias="minDigits")
    """
    Minimum number of DTMF digits required.
    """
    max_digits: float | None = Field(default=None, alias="maxDigits")
    """
    Maximum number of DTMF digits to collect.
    """
    inter_digit_timeout: float | None = Field(default=None, alias="interDigitTimeout", examples=[5])
    """
    Time in seconds to wait between DTMF digits before considering input complete.
    """
    speech_timeout: float | None = Field(default=None, alias="speechTimeout", examples=[2, 3])
    """
    Time in seconds of silence after speech before considering the utterance complete.
    """
    timeout: float | None = Field(default=None, examples=[10, 30])
    """
    Overall timeout in seconds. If no input is received within this time, the gather completes with no input and the actionHook is invoked.
    """
    partial_result_hook: actionHook.ActionHook | None = Field(
        default=None, alias="partialResultHook"
    )
    """
    A webhook to invoke with interim (partial) speech recognition results. Useful for providing real-time feedback or early processing.
    """
    listen_during_prompt: bool | None = Field(default=True, alias="listenDuringPrompt")
    """
    If true, listen for input while the prompt is playing. If false, only start listening after the prompt finishes.
    """
    dtmf_bargein: bool | None = Field(default=None, alias="dtmfBargein")
    """
    If true, DTMF input interrupts (barges in on) any playing prompt.
    """
    bargein: bool | None = None
    """
    If true, speech input interrupts (barges in on) any playing prompt.
    """
    min_bargein_word_count: float | None = Field(
        default=None, alias="minBargeinWordCount", examples=[1, 2]
    )
    """
    Minimum number of words that must be recognized before barge-in is triggered. Prevents brief noises from interrupting prompts.
    """
    recognizer: recognizer_1.Recognizer | None = None
    """
    Override the session-level STT configuration for this gather.
    """
    say: Say | None = None
    """
    A nested say prompt played to the caller while listening for input. Accepts the same properties as the say verb (text, synthesizer, etc.) but no fields are required.
    """
    play: Play | None = None
    """
    A nested play prompt played to the caller while listening for input. Accepts the same properties as the play verb (url, etc.) but no fields are required.
    """
    filler_noise: fillerNoise.FillerNoise | None = Field(default=None, alias="fillerNoise")
    """
    Filler noise configuration while waiting for the actionHook to respond.
    """
    action_hook_delay_action: actionHookDelayAction.ActionHookDelayAction | None = Field(
        default=None, alias="actionHookDelayAction"
    )
    """
    Configuration for interim actions while the actionHook is processing.
    """

    @model_validator(mode="after")
    def _check_digit_bounds(self) -> Gather:
        """``numDigits`` is mutually exclusive with ``min/maxDigits``."""
        if self.num_digits is not None and (
            self.min_digits is not None or self.max_digits is not None
        ):
            raise ValueError("numDigits cannot be combined with minDigits or maxDigits")
        if (
            self.min_digits is not None
            and self.max_digits is not None
            and self.min_digits > self.max_digits
        ):
            raise ValueError("minDigits cannot exceed maxDigits")
        return self
