# generated by datamodel-codegen:
#   filename:  verbs/hangup
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from jambonz_sdk._models.base import JambonzModel


class Hangup(JambonzModel):
    """
    Terminates the call. Optionally includes custom SIP headers on the BYE request.
    """

    verb: Literal["hangup"] = "hangup"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    headers: dict[str, str | float] | None = None
    """
    Custom SIP headers to include on the BYE request.
    """
