# generated by datamodel-codegen:
#   filename:  verbs/leave
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from jambonz_sdk._models.base import JambonzModel


class Leave(JambonzModel):
    """
    Removes the caller from a conference or queue that they are currently in. Execution continues with the next verb in the application.
    """

    verb: Literal["leave"] = "leave"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
