# generated by datamodel-codegen:
#   filename:  verbs/listen
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import Field

from ..components import actionHook, auth, bidirectionalAudio
from . import transcribe as transcribe_1
from jambonz_sdk._models.base import JambonzModel


class MixType(Enum):
    """
    How to mix the audio channels when streaming. 'mono' sends a single mixed channel, 'stereo' sends caller and callee as separate left/right channels, 'mixed' sends both as a single mixed stream.
    """

    mono = "mono"
    stereo = "stereo"
    mixed = "mixed"


class Listen(JambonzModel):
    """
    Streams real-time call audio to an external websocket endpoint. The remote endpoint receives raw audio and can optionally send audio back (bidirectional). Used for custom speech processing, real-time analysis, AI agent integration, and recording to external systems.
    """

    verb: Literal["listen"] = "listen"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    url: str = Field(..., examples=["wss://myapp.example.com/audio-stream"])
    """
    The websocket URL to stream audio to.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the listen session ends. Should return the next verbs to execute.
    """
    ws_auth: auth.Auth | None = Field(default=None, alias="wsAuth")
    """
    Authentication credentials for the websocket connection.
    """
    mix_type: MixType | None = Field(default="mono", alias="mixType")
    """
    How to mix the audio channels when streaming. 'mono' sends a single mixed channel, 'stereo' sends caller and callee as separate left/right channels, 'mixed' sends both as a single mixed stream.
    """
    metadata: dict[str, Any] | None = None
    """
    Arbitrary metadata to send to the websocket endpoint in the initial connection message.
    """
    sample_rate: float | None = Field(
        default=8000, alias="sampleRate", examples=[8000, 16000, 24000]
    )
    """
    The audio sample rate in Hz.
    """
    finish_on_key: str | None = Field(default=None, alias="finishOnKey", examples=["#"])
    """
    A DTMF key that ends the listen session when pressed.
    """
    max_length: float | None = Field(default=None, alias="maxLength")
    """
    Maximum duration in seconds for the listen session.
    """
    pass_dtmf: bool | None = Field(default=None, alias="passDtmf")
    """
    If true, forward DTMF events to the websocket endpoint.
    """
    play_beep: bool | None = Field(default=None, alias="playBeep")
    """
    If true, play a beep tone before streaming begins.
    """
    disable_bidirectional_audio: bool | None = Field(
        default=None, alias="disableBidirectionalAudio"
    )
    """
    If true, disable receiving audio from the websocket endpoint. Audio flows only from the call to the websocket, not back.
    """
    bidirectional_audio: bidirectionalAudio.BidirectionalAudio | None = Field(
        default=None, alias="bidirectionalAudio"
    )
    """
    Fine-grained configuration for bidirectional audio.
    """
    timeout: float | None = None
    """
    Time in seconds to wait for audio activity before ending the listen session.
    """
    transcribe: transcribe_1.Transcribe | None = None
    """
    Nested transcribe verb — enables simultaneous real-time transcription of the audio being streamed.
    """
    early_media: bool | None = Field(default=None, alias="earlyMedia")
    """
    If true, begin streaming audio before the call is formally answered.
    """
    channel: float | None = None
    """
    Specific audio channel to stream. Used when streaming a single channel of a multi-channel call.
    """
