# generated by datamodel-codegen:
#   filename:  verbs/llm
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from ..components.llm_base import LlmBaseProperties


class LLM(LlmBaseProperties):
    """
    Connects the caller to a large language model for a real-time voice conversation. Handles the complete STT → LLM → TTS pipeline, including turn detection, interruption handling, and tool/function calling. The caller speaks naturally and the LLM responds via synthesized speech. This is the primary verb for building AI voice agents on jambonz.
    """

    verb: Literal["llm"] = "llm"
    """
    The verb name.
    """
    vendor: str = Field(
        ...,
        examples=[
            "openai",
            "anthropic",
            "google",
            "groq",
            "deepseek",
            "deepgram",
            "ultravox",
            "custom",
        ],
    )
    """
    The LLM vendor to use.
    """
    llm_options: dict[str, Any] = Field(
        ...,
        alias="llmOptions",
        examples=[
            {
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful customer service agent for Acme Corp.",
                    }
                ],
                "temperature": 0.7,
            }
        ],
    )
    """
    Configuration passed to the LLM including the system prompt, temperature, tools/functions, and other model parameters. The structure varies by vendor but typically includes 'messages' (conversation history), 'temperature', 'tools' (function definitions), and 'maxTokens'.
    """
