# generated by datamodel-codegen:
#   filename:  verbs/message
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel

from ..components import actionHook


class Message(JambonzModel):
    """
    Sends an SMS or MMS message. Can be used during a voice call to send a text message to the caller or another party, or as a standalone action.
    """

    verb: Literal["message"] = "message"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    to: str = Field(..., examples=["+15085551212"])
    """
    The destination phone number in E.164 format.
    """
    from_: str = Field(..., alias="from", examples=["+15085559876"])
    """
    The sender phone number in E.164 format. Must be a number provisioned on the jambonz platform.
    """
    text: str | None = None
    """
    The text content of the message.
    """
    media: str | list[str] | None = Field(
        default=None, examples=["https://example.com/images/receipt.png"]
    )
    """
    URL(s) of media to attach to the message (MMS). Can be images, audio, or video.
    """
    carrier: str | None = None
    """
    The messaging carrier to use. If not specified, the default carrier is used.
    """
    account_sid: str | None = None
    """
    The account SID to use for sending. Defaults to the current account.
    """
    message_sid: str | None = None
    """
    An optional message SID for tracking.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the message send completes or fails.
    """
