# generated by datamodel-codegen:
#   filename:  verbs/openai_s2s
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from ..components.llm_base import LlmBaseProperties


class OpenaiS2S(LlmBaseProperties):
    """
    Shortcut for 'llm' with vendor automatically set to 'openai'. Connects the caller to an OpenAI model for real-time speech-to-speech voice conversation.
    """

    verb: Literal["openai_s2s"] = "openai_s2s"
    """
    The verb name.
    """
    vendor: Literal["openai"] = "openai"
    """
    The LLM vendor (always 'openai' for this shortcut).
    """
    llm_options: dict[str, Any] = Field(
        ...,
        alias="llmOptions",
        examples=[
            {
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful customer service agent for Acme Corp.",
                    }
                ],
                "temperature": 0.7,
            }
        ],
    )
    """
    Configuration passed to the LLM including the system prompt, temperature, tools/functions, and other model parameters. The structure varies by vendor but typically includes 'messages' (conversation history), 'temperature', 'tools' (function definitions), and 'maxTokens'.
    """
