# generated by datamodel-codegen:
#   filename:  verbs/pause
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel


class Pause(JambonzModel):
    """
    Pauses execution for a specified number of seconds. The caller hears silence during the pause. Useful for adding delays between verbs.
    """

    verb: Literal["pause"] = "pause"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    length: float = Field(..., examples=[1, 2, 5])
    """
    The duration of the pause in seconds.
    """
