# generated by datamodel-codegen:
#   filename:  verbs/play
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel

from ..components import actionHook


class Play(JambonzModel):
    """
    Plays an audio file to the caller. Supports WAV and MP3 formats hosted at a URL. Can play a single file or cycle through a list of files.
    """

    verb: Literal["play"] = "play"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    url: str | list[str] = Field(
        ...,
        examples=[
            "https://example.com/sounds/greeting.wav",
            [
                "https://example.com/sounds/part1.wav",
                "https://example.com/sounds/part2.wav",
            ],
        ],
    )
    """
    The URL(s) of the audio file(s) to play. Supports WAV and MP3. If an array, files are played in sequence.
    """
    loop: float | str | None = Field(default=None, examples=[3, "forever"])
    """
    Number of times to repeat playback. Use 0 or 'forever' to loop indefinitely until interrupted.
    """
    early_media: bool | None = Field(default=None, alias="earlyMedia")
    """
    If true, play the audio as early media before the call is answered.
    """
    seek_offset: float | str | None = Field(default=None, alias="seekOffset")
    """
    Start playback at this offset in seconds from the beginning of the file.
    """
    timeout_secs: float | str | None = Field(default=None, alias="timeoutSecs")
    """
    Maximum time in seconds to play the audio. Playback stops after this duration even if the file has not finished.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook to invoke when playback completes.
    """
