# generated by datamodel-codegen:
#   filename:  verbs/redirect
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel

from ..components import actionHook


class Redirect(JambonzModel):
    """
    Transfers call control to a different webhook URL. The current verb stack is abandoned and the new webhook's response becomes the active application. Useful for modular application design where different URLs handle different phases of a call.
    """

    verb: Literal["redirect"] = "redirect"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    action_hook: actionHook.ActionHook = Field(..., alias="actionHook")
    """
    The webhook to transfer control to. Must return a new array of verbs.
    """
    status_hook: actionHook.ActionHook | None = Field(default=None, alias="statusHook")
    """
    A webhook to receive call status events after the redirect.
    """
