# generated by datamodel-codegen:
#   filename:  verbs/rest:dial
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel

from ..components import amd as amd_1
from ..components import target


class RestDial(JambonzModel):
    """
    Internal verb used to originate an outbound call via the REST API. Not typically used directly in application verb arrays.
    """

    verb: Literal["rest:dial"] = "rest:dial"
    id: str | None = None
    account_sid: str | None = None
    application_sid: str | None = None
    call_hook: str | dict[str, Any]
    """
    Webhook URL or object for call control.
    """
    call_status_hook: str | dict[str, Any] | None = None
    """
    Webhook URL or object for call status notifications.
    """
    from_: str = Field(..., alias="from")
    """
    The caller ID for the outbound call.
    """
    caller_name: str | None = Field(default=None, alias="callerName")
    """
    Display name for the caller.
    """
    from_host: str | None = Field(default=None, alias="fromHost")
    """
    SIP host to use in the From header.
    """
    speech_synthesis_vendor: str | None = None
    speech_synthesis_voice: str | None = None
    speech_synthesis_language: str | None = None
    speech_recognizer_vendor: str | None = None
    speech_recognizer_language: str | None = None
    tag: dict[str, Any] | None = None
    """
    Arbitrary metadata to attach to the call.
    """
    to: target.Target
    """
    The call destination.
    """
    headers: dict[str, str | float] | None = None
    """
    Custom SIP headers to include on the outbound INVITE.
    """
    timeout: float | None = None
    """
    Ring timeout in seconds.
    """
    amd: amd_1.AnsweringMachineDetection | None = None
    """
    Answering machine detection configuration.
    """
    dual_streams: bool | None = None
    """
    If true, send separate audio streams for each call leg.
    """
    sip_request_within_dialog_hook: str | None = Field(
        default=None, alias="sipRequestWithinDialogHook"
    )
    """
    Webhook for in-dialog SIP requests.
    """
    refer_hook: str | dict[str, Any] | None = Field(default=None, alias="referHook")
    """
    Webhook for SIP REFER handling.
    """
    time_limit: float | None = Field(default=None, alias="timeLimit")
    """
    Maximum call duration in seconds.
    """
