# generated by datamodel-codegen:
#   filename:  verbs/s2s
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from ..components.llm_base import LlmBaseProperties


class S2S(LlmBaseProperties):
    """
    Synonym for 'llm'. Connects the caller to a large language model for a real-time speech-to-speech voice conversation. Requires 'vendor' to be specified explicitly.
    """

    verb: Literal["s2s"] = "s2s"
    """
    The verb name.
    """
    vendor: str = Field(
        ...,
        examples=[
            "openai",
            "anthropic",
            "google",
            "groq",
            "deepseek",
            "deepgram",
            "ultravox",
            "custom",
        ],
    )
    """
    The LLM vendor to use.
    """
    llm_options: dict[str, Any] = Field(
        ...,
        alias="llmOptions",
        examples=[
            {
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful customer service agent for Acme Corp.",
                    }
                ],
                "temperature": 0.7,
            }
        ],
    )
    """
    Configuration passed to the LLM including the system prompt, temperature, tools/functions, and other model parameters. The structure varies by vendor but typically includes 'messages' (conversation history), 'temperature', 'tools' (function definitions), and 'maxTokens'.
    """
