# generated by datamodel-codegen:
#   filename:  verbs/say
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ..components import synthesizer as synthesizer_1
from jambonz_sdk._models.base import JambonzModel


class Say(JambonzModel):
    """
    Speaks text to the caller using text-to-speech. The text can be plain text or SSML. Optionally streams TTS output incrementally for lower latency. This is one of the most commonly used verbs in jambonz applications.
    """

    verb: Literal["say"] = "say"
    """
    The verb name.
    """
    id: str | None = None
    """
    An optional unique identifier for this verb instance. Can be used to reference it in other contexts.
    """
    text: str | list[str] | None = Field(
        default=None,
        examples=[
            "Hello, welcome to our service.",
            "<speak>Hello <break time='500ms'/> welcome.</speak>",
            ["Hello!", "Hi there!", "Welcome!"],
        ],
    )
    """
    The text to speak. Can be plain text or SSML markup. If an array is provided, one entry is selected at random (useful for variety in prompts).
    """
    instructions: str | None = Field(
        default=None, examples=["Speak in a warm, friendly tone", "Sound excited and energetic"]
    )
    """
    Natural language instructions to guide TTS expression and delivery. Supported by vendors that offer instruction-based synthesis (e.g. ElevenLabs, some OpenAI models).
    """
    stream: bool | None = None
    """
    If true, stream TTS audio to the caller incrementally as it is generated, rather than waiting for the complete audio. Reduces time-to-first-byte for long utterances. Requires a vendor that supports streaming synthesis.
    """
    loop: float | str | None = Field(default=None, examples=[2, "forever"])
    """
    Number of times to repeat the speech. Use 0 or 'forever' to loop indefinitely until interrupted.
    """
    synthesizer: synthesizer_1.Synthesizer | None = None
    """
    Override the session-level TTS configuration for this specific utterance.
    """
    early_media: bool | None = Field(default=None, alias="earlyMedia")
    """
    If true, play the audio as early media (before the call is answered). Used for playing announcements or prompts to the caller before the call is formally connected.
    """
    disable_tts_cache: bool | None = Field(default=None, alias="disableTtsCache")
    """
    If true, bypass the TTS cache and always generate fresh audio. Useful when the same text should be re-synthesized (e.g. with different SSML or when the voice has been updated).
    """
    close_stream_on_empty: bool | None = Field(default=None, alias="closeStreamOnEmpty")
    """
    If true, close the TTS stream when an empty text string is received. Only applies when stream is true.
    """
