# generated by datamodel-codegen:
#   filename:  verbs/sip-decline
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field
from jambonz_sdk._models.base import JambonzModel


class SipDecline(JambonzModel):
    """
    Rejects an incoming call with a SIP error response. Used to decline calls with a specific status code and reason (e.g. 486 Busy Here, 603 Decline).
    """

    verb: Literal["sip:decline"] = "sip:decline"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    status: float = Field(..., examples=[486, 603, 404, 480])
    """
    The SIP response status code to send.
    """
    reason: str | None = Field(default=None, examples=["Busy Here", "Decline", "Not Found"])
    """
    The SIP reason phrase to include in the response.
    """
    headers: dict[str, str | float] | None = None
    """
    Custom SIP headers to include in the response.
    """
