# generated by datamodel-codegen:
#   filename:  verbs/sip-request
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ..components import actionHook
from jambonz_sdk._models.base import JambonzModel


class SipRequest(JambonzModel):
    """
    Sends a SIP request within the current dialog. Used to send INFO, NOTIFY, or other SIP methods to the remote party during an active call.
    """

    verb: Literal["sip:request"] = "sip:request"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    method: str = Field(..., examples=["INFO", "NOTIFY", "MESSAGE"])
    """
    The SIP method to send.
    """
    body: str | None = None
    """
    The body of the SIP request.
    """
    headers: dict[str, str | float] | None = None
    """
    Custom SIP headers to include in the request.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the response to the SIP request is received.
    """
