# generated by datamodel-codegen:
#   filename:  verbs/sip-refer
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ..components import actionHook
from jambonz_sdk._models.base import JambonzModel


class SipRefer(JambonzModel):
    """
    Sends a SIP REFER request to transfer the call to another party. Initiates an attended or unattended (blind) transfer.
    """

    verb: Literal["sip:refer"] = "sip:refer"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    refer_to: str = Field(..., alias="referTo", examples=["sip:alice@example.com", "+15085551212"])
    """
    The SIP URI or phone number to transfer the call to.
    """
    referred_by: str | None = Field(default=None, alias="referredBy")
    """
    The SIP URI to use in the Referred-By header.
    """
    referred_by_display_name: str | None = Field(default=None, alias="referredByDisplayName")
    """
    The display name to use in the Referred-By header.
    """
    headers: dict[str, str | float] | None = None
    """
    Custom SIP headers to include in the REFER request.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the REFER completes (or fails).
    """
    event_hook: actionHook.ActionHook | None = Field(default=None, alias="eventHook")
    """
    A webhook invoked for NOTIFY events during the REFER process, providing transfer progress updates.
    """
