# generated by datamodel-codegen:
#   filename:  verbs/stream
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel

from ..components import actionHook, auth, bidirectionalAudio
from . import transcribe as transcribe_1


class MixType(Enum):
    """
    How to mix audio channels.
    """

    mono = "mono"
    stereo = "stereo"
    mixed = "mixed"


class Stream(JambonzModel):
    """
    Streams real-time call audio to an external websocket endpoint. Functionally equivalent to 'listen' — this is an alias provided for naming clarity when the intent is audio streaming rather than recording.
    """

    verb: Literal["stream"] = "stream"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    url: str
    """
    The websocket URL to stream audio to.
    """
    action_hook: actionHook.ActionHook | None = Field(default=None, alias="actionHook")
    """
    A webhook invoked when the stream ends.
    """
    ws_auth: auth.Auth | None = Field(default=None, alias="wsAuth")
    """
    Authentication credentials for the websocket connection.
    """
    mix_type: MixType | None = Field(default=None, alias="mixType")
    """
    How to mix audio channels.
    """
    metadata: dict[str, Any] | None = None
    """
    Metadata to send with the initial connection.
    """
    sample_rate: float | None = Field(default=None, alias="sampleRate", examples=[8000, 16000])
    """
    Audio sample rate in Hz.
    """
    finish_on_key: str | None = Field(default=None, alias="finishOnKey")
    """
    DTMF key that ends the stream.
    """
    max_length: float | None = Field(default=None, alias="maxLength")
    """
    Maximum duration in seconds.
    """
    pass_dtmf: bool | None = Field(default=None, alias="passDtmf")
    """
    Forward DTMF events to the websocket.
    """
    play_beep: bool | None = Field(default=None, alias="playBeep")
    """
    Play a beep before streaming begins.
    """
    disable_bidirectional_audio: bool | None = Field(
        default=None, alias="disableBidirectionalAudio"
    )
    """
    Disable receiving audio from the websocket.
    """
    bidirectional_audio: bidirectionalAudio.BidirectionalAudio | None = Field(
        default=None, alias="bidirectionalAudio"
    )
    """
    Bidirectional audio configuration.
    """
    timeout: float | None = None
    """
    Inactivity timeout in seconds.
    """
    transcribe: transcribe_1.Transcribe | None = None
    """
    Nested transcribe verb — enables simultaneous real-time transcription of the streamed audio.
    """
    early_media: bool | None = Field(default=None, alias="earlyMedia")
    """
    Stream audio before the call is answered.
    """
    channel: float | None = None
    """
    Specific audio channel to stream. Used when streaming a single channel of a multi-channel call.
    """
