# generated by datamodel-codegen:
#   filename:  verbs/tag
#   timestamp: 2026-05-19T13:39:55+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from jambonz_sdk._models.base import JambonzModel


class Tag(JambonzModel):
    """
    Attaches arbitrary metadata to the current call. Tagged data is included in all subsequent webhook requests and in the call detail record (CDR). Useful for tracking business context, routing decisions, or analytics data through the call lifecycle.
    """

    verb: Literal["tag"] = "tag"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    data: dict[str, Any] = Field(
        ...,
        examples=[{"customerId": "12345", "department": "support", "priority": "high"}],
    )
    """
    An object containing the metadata to attach to the call. Keys and values are application-defined.
    """
