# generated by datamodel-codegen:
#   filename:  verbs/transcribe
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ..components import recognizer as recognizer_1
from jambonz_sdk._models.base import JambonzModel


class Transcribe(JambonzModel):
    """
    Enables real-time transcription of the call audio. Transcription results are sent to the transcriptionHook as they are produced. Runs as a background process — subsequent verbs execute immediately while transcription continues.
    """

    verb: Literal["transcribe"] = "transcribe"
    id: str | None = None
    """
    An optional unique identifier for this verb instance.
    """
    enable: bool | None = None
    """
    Enable or disable transcription. Used when transcribe is nested inside a config or dial verb to start or stop background transcription.
    """
    transcription_hook: str | None = Field(default=None, alias="transcriptionHook")
    """
    The webhook URL to receive transcription results.
    """
    translation_hook: str | None = Field(default=None, alias="translationHook")
    """
    The webhook URL to receive translated transcription results.
    """
    recognizer: recognizer_1.Recognizer | None = None
    """
    STT configuration for the transcription.
    """
    early_media: bool | None = Field(default=None, alias="earlyMedia")
    """
    If true, begin transcribing before the call is answered.
    """
    channel: float | None = None
    """
    Specific audio channel to transcribe.
    """
