# generated by datamodel-codegen:
#   filename:  jambonz-app
#   timestamp: 2026-04-22T10:54:53+00:00

from __future__ import annotations

from pydantic import Field, RootModel

from .verbs import (
    agent,
    alert,
    answer,
    conference,
    config,
    deepgram_s2s,
    dequeue,
    dial,
    dialogflow,
    dtmf,
    dub,
    elevenlabs_s2s,
    enqueue,
    gather,
    google_s2s,
    hangup,
    leave,
    listen,
    llm,
    message,
    openai_s2s,
    pause,
    play,
    redirect,
    rest_dial,
    s2s,
    say,
    sip_decline,
    sip_refer,
    sip_request,
    stream,
    tag,
    transcribe,
    ultravox_s2s,
)


class Verb(
    RootModel[
        answer.Answer
        | alert.Alert
        | config.Config
        | say.Say
        | play.Play
        | gather.Gather
        | dial.Dial
        | listen.Listen
        | stream.Stream
        | llm.LLM
        | s2s.S2S
        | openai_s2s.OpenaiS2S
        | google_s2s.GoogleS2S
        | elevenlabs_s2s.ElevenlabsS2S
        | deepgram_s2s.DeepgramS2S
        | ultravox_s2s.UltravoxS2S
        | dialogflow.Dialogflow
        | agent.Agent
        | conference.Conference
        | transcribe.Transcribe
        | enqueue.Enqueue
        | dequeue.Dequeue
        | dtmf.DTMF
        | dub.Dub
        | hangup.Hangup
        | leave.Leave
        | message.Message
        | pause.Pause
        | redirect.Redirect
        | tag.Tag
        | sip_decline.SipDecline
        | sip_request.SipRequest
        | sip_refer.SipRefer
        | rest_dial.RestDial
    ]
):
    root: (
        answer.Answer
        | alert.Alert
        | config.Config
        | say.Say
        | play.Play
        | gather.Gather
        | dial.Dial
        | listen.Listen
        | stream.Stream
        | llm.LLM
        | s2s.S2S
        | openai_s2s.OpenaiS2S
        | google_s2s.GoogleS2S
        | elevenlabs_s2s.ElevenlabsS2S
        | deepgram_s2s.DeepgramS2S
        | ultravox_s2s.UltravoxS2S
        | dialogflow.Dialogflow
        | agent.Agent
        | conference.Conference
        | transcribe.Transcribe
        | enqueue.Enqueue
        | dequeue.Dequeue
        | dtmf.DTMF
        | dub.Dub
        | hangup.Hangup
        | leave.Leave
        | message.Message
        | pause.Pause
        | redirect.Redirect
        | tag.Tag
        | sip_decline.SipDecline
        | sip_request.SipRequest
        | sip_refer.SipRefer
        | rest_dial.RestDial
    ) = Field(..., discriminator="verb")


class JambonzApplication(RootModel[list[Verb]]):
    """
    A jambonz application is an array of verbs that are executed sequentially to control a phone call. Each verb performs an action: speaking text, playing audio, collecting input, dialing a number, connecting to an AI model, etc. When a webhook (actionHook) is invoked, it must return a new verb array to continue call processing.

    The execution model is simple: verbs execute one after another, top to bottom. When a verb with an actionHook completes (e.g. gather collects input), the actionHook is called and its response replaces the remaining verb stack. If the verb array is exhausted without a hangup, the call is terminated.

    There are two transport modes for delivering verb arrays to jambonz:
    - **Webhook**: Your HTTP server receives POST/GET requests with call data and returns JSON verb arrays in the response body.
    - **WebSocket**: Your server maintains a persistent websocket connection with jambonz and sends/receives verb arrays as JSON messages. Required for real-time features like LLM conversations.

    The verb schemas and JSON structure are identical regardless of transport mode.
    """

    root: list[Verb] = Field(
        ...,
        examples=[
            [
                {
                    "verb": "config",
                    "synthesizer": {
                        "vendor": "elevenlabs",
                        "voice": "EXAVITQu4vr4xnSDxMaL",
                        "language": "en-US",
                    },
                    "recognizer": {"vendor": "deepgram", "language": "en-US"},
                },
                {
                    "verb": "say",
                    "text": "Hello! Welcome to Acme Corp. How can I help you today?",
                },
                {
                    "verb": "gather",
                    "input": ["speech"],
                    "actionHook": "/process-input",
                    "timeout": 15,
                    "say": {"text": "I'm listening."},
                },
            ],
            [
                {"verb": "say", "text": "Please hold while I connect you to an agent."},
                {
                    "verb": "dial",
                    "target": [{"type": "phone", "number": "+15085551212"}],
                    "answerOnBridge": True,
                    "timeout": 30,
                    "actionHook": "/dial-complete",
                },
                {
                    "verb": "say",
                    "text": "Sorry, the agent is not available. Please try again later.",
                },
                {"verb": "hangup"},
            ],
            [
                {
                    "verb": "config",
                    "synthesizer": {"vendor": "cartesia", "voice": "sonic-english"},
                    "recognizer": {"vendor": "deepgram", "language": "en-US"},
                },
                {
                    "verb": "openai_s2s",
                    "model": "gpt-4o",
                    "llmOptions": {
                        "messages": [
                            {
                                "role": "system",
                                "content": "You are a helpful customer service agent for Acme Corp. Be concise and friendly.",
                            }
                        ],
                        "temperature": 0.7,
                    },
                    "actionHook": "/llm-complete",
                    "toolHook": "/llm-tool",
                },
            ],
        ],
        min_length=1,
        title="jambonz Application",
    )
    """
    A jambonz application is an array of verbs that are executed sequentially to control a phone call. Each verb performs an action: speaking text, playing audio, collecting input, dialing a number, connecting to an AI model, etc. When a webhook (actionHook) is invoked, it must return a new verb array to continue call processing.

    The execution model is simple: verbs execute one after another, top to bottom. When a verb with an actionHook completes (e.g. gather collects input), the actionHook is called and its response replaces the remaining verb stack. If the verb array is exhausted without a hangup, the call is terminated.

    There are two transport modes for delivering verb arrays to jambonz:
    - **Webhook**: Your HTTP server receives POST/GET requests with call data and returns JSON verb arrays in the response body.
    - **WebSocket**: Your server maintains a persistent websocket connection with jambonz and sends/receives verb arrays as JSON messages. Required for real-time features like LLM conversations.

    The verb schemas and JSON structure are identical regardless of transport mode.
    """
